import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const catalogPath = path.join(__dirname, '../src/data/stockCatalog.json');
const currentCatalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));

// Filter out old non-KR items to replace with complete curated list
const krStocks = currentCatalog.filter(s => s.country === 'KR');

// 1. UNITED STATES (US) - Top 120+ S&P500 & Nasdaq 100 Leaders
const usStocks = [
  // Big Tech & Semis
  { country: 'US', ticker: 'AAPL', name: 'Apple Inc.', koreanName: '애플', industry: '소프트웨어', targetPe: 28 },
  { country: 'US', ticker: 'MSFT', name: 'Microsoft Corporation', koreanName: '마이크로소프트', industry: '소프트웨어', targetPe: 32 },
  { country: 'US', ticker: 'NVDA', name: 'NVIDIA Corporation', koreanName: '엔비디아', industry: '반도체', targetPe: 40 },
  { country: 'US', ticker: 'GOOGL', name: 'Alphabet Inc. (Class A)', koreanName: '알파벳 A (구글)', industry: '인터넷/미디어', targetPe: 24 },
  { country: 'US', ticker: 'GOOG', name: 'Alphabet Inc. (Class C)', koreanName: '알파벳 C (구글)', industry: '인터넷/미디어', targetPe: 24 },
  { country: 'US', ticker: 'AMZN', name: 'Amazon.com Inc.', koreanName: '아마존', industry: '이커머스/클라우드', targetPe: 35 },
  { country: 'US', ticker: 'META', name: 'Meta Platforms Inc.', koreanName: '메타 (페이스북)', industry: '인터넷/소셜미디어', targetPe: 25 },
  { country: 'US', ticker: 'TSLA', name: 'Tesla Inc.', koreanName: '테슬라', industry: '전기차/에너지', targetPe: 45 },
  { country: 'US', ticker: 'AVGO', name: 'Broadcom Inc.', koreanName: '브로드컴', industry: '반도체', targetPe: 28 },
  { country: 'US', ticker: 'TSM', name: 'Taiwan Semiconductor (ADR)', koreanName: 'TSMC', industry: '반도체파운드리', targetPe: 25 },
  { country: 'US', ticker: 'ASML', name: 'ASML Holding (ADR)', koreanName: 'ASML', industry: '반도체장비', targetPe: 35 },
  { country: 'US', ticker: 'AMD', name: 'Advanced Micro Devices', koreanName: 'AMD', industry: '반도체', targetPe: 35 },
  { country: 'US', ticker: 'QCOM', name: 'Qualcomm Inc.', koreanName: '퀄컴', industry: '반도체', targetPe: 18 },
  { country: 'US', ticker: 'TXN', name: 'Texas Instruments', koreanName: '텍사스 인스트루먼트', industry: '반도체', targetPe: 25 },
  { country: 'US', ticker: 'INTC', name: 'Intel Corporation', koreanName: '인텔', industry: '반도체', targetPe: 15 },
  { country: 'US', ticker: 'AMAT', name: 'Applied Materials', koreanName: '어플라이드 머티어리얼즈', industry: '반도체장비', targetPe: 22 },
  { country: 'US', ticker: 'LRCX', name: 'Lam Research Corp.', koreanName: '램리서치', industry: '반도체장비', targetPe: 24 },
  { country: 'US', ticker: 'MU', name: 'Micron Technology', koreanName: '마이크론 테크놀로지', industry: '메모리반도체', targetPe: 15 },
  { country: 'US', ticker: 'ARM', name: 'Arm Holdings plc (ADR)', koreanName: 'ARM 홀딩스', industry: '반도체설계', targetPe: 45 },
  { country: 'US', ticker: 'PLTR', name: 'Palantir Technologies', koreanName: '팔란티어', industry: 'AI소프트웨어', targetPe: 50 },
  { country: 'US', ticker: 'ORCL', name: 'Oracle Corporation', koreanName: '오라클', industry: '데이터베이스/클라우드', targetPe: 25 },
  { country: 'US', ticker: 'CRM', name: 'Salesforce Inc.', koreanName: '세일즈포스', industry: '클라우드CRM', targetPe: 28 },
  { country: 'US', ticker: 'ADBE', name: 'Adobe Inc.', koreanName: '어도비', industry: '소프트웨어', targetPe: 30 },
  { country: 'US', ticker: 'NOW', name: 'ServiceNow Inc.', koreanName: '서비스나우', industry: '클라우드소프트웨어', targetPe: 45 },
  { country: 'US', ticker: 'PANW', name: 'Palo Alto Networks', koreanName: '팔로알토 네트웍스', industry: '사이버보안', targetPe: 40 },
  { country: 'US', ticker: 'CRWD', name: 'CrowdStrike Holdings', koreanName: '크라우드스트라이크', industry: '사이버보안', targetPe: 50 },
  { country: 'US', ticker: 'SNPS', name: 'Synopsys Inc.', koreanName: '시놉시스', industry: '반도체EDA', targetPe: 35 },
  { country: 'US', ticker: 'CDNS', name: 'Cadence Design Systems', koreanName: '케이던스 디자인', industry: '반도체EDA', targetPe: 35 },
  { country: 'US', ticker: 'INTU', name: 'Intuit Inc.', koreanName: '인튜이트', industry: '핀테크소프트웨어', targetPe: 30 },
  { country: 'US', ticker: 'IBM', name: 'International Business Machines', koreanName: 'IBM', industry: 'IT서비스/하드웨어', targetPe: 18 },
  { country: 'US', ticker: 'CSCO', name: 'Cisco Systems', koreanName: '시스코', industry: '네트워크장비', targetPe: 16 },
  { country: 'US', ticker: 'ACN', name: 'Accenture plc', koreanName: '액센츄어', industry: 'IT컨설팅', targetPe: 25 },
  { country: 'US', ticker: 'APP', name: 'AppLovin Corporation', koreanName: '앱러빈', industry: 'AI광고기술', targetPe: 30 },

  // Healthcare & Pharma
  { country: 'US', ticker: 'LLY', name: 'Eli Lilly and Company', koreanName: '일라이 릴리', industry: '바이오/제약', targetPe: 40 },
  { country: 'US', ticker: 'UNH', name: 'UnitedHealth Group', koreanName: '유나이티드헬스그룹', industry: '헬스케어서비스', targetPe: 20 },
  { country: 'US', ticker: 'JNJ', name: 'Johnson & Johnson', koreanName: '존슨앤존슨', industry: '의약품/의료기기', targetPe: 17 },
  { country: 'US', ticker: 'ABBV', name: 'AbbVie Inc.', koreanName: '애브비', industry: '바이오/제약', targetPe: 16 },
  { country: 'US', ticker: 'MRK', name: 'Merck & Co. Inc.', koreanName: '머크', industry: '바이오/제약', targetPe: 16 },
  { country: 'US', ticker: 'TMO', name: 'Thermo Fisher Scientific', koreanName: '써모피셔 사이언티픽', industry: '의료기기/진단', targetPe: 26 },
  { country: 'US', ticker: 'ABT', name: 'Abbott Laboratories', koreanName: '애보트', industry: '의료기기/진단', targetPe: 24 },
  { country: 'US', ticker: 'DHR', name: 'Danaher Corporation', koreanName: '다나허', industry: '생명공학/진단', targetPe: 28 },
  { country: 'US', ticker: 'PFE', name: 'Pfizer Inc.', koreanName: '화이자', industry: '바이오/제약', targetPe: 14 },
  { country: 'US', ticker: 'ISRG', name: 'Intuitive Surgical', koreanName: '인튜이티브 서지컬 (다빈치 로봇)', industry: '수술로봇/의료기기', targetPe: 45 },
  { country: 'US', ticker: 'AMGN', name: 'Amgen Inc.', koreanName: '암젠', industry: '바이오/제약', targetPe: 16 },
  { country: 'US', ticker: 'BMY', name: 'Bristol-Myers Squibb', koreanName: '브리스톨 마이어스 스퀴브', industry: '바이오/제약', targetPe: 14 },
  { country: 'US', ticker: 'GILD', name: 'Gilead Sciences', koreanName: '길리어드 사이언스', industry: '바이오/제약', targetPe: 15 },
  { country: 'US', ticker: 'VRTX', name: 'Vertex Pharmaceuticals', koreanName: '버텍스 파마슈티컬스', industry: '희귀질환바이오', targetPe: 28 },
  { country: 'US', ticker: 'REGN', name: 'Regeneron Pharmaceuticals', koreanName: '리제네론', industry: '바이오/제약', targetPe: 22 },
  { country: 'US', ticker: 'MDT', name: 'Medtronic plc', koreanName: '메드트로닉', industry: '의료기기', targetPe: 18 },

  // Financials & Payments
  { country: 'US', ticker: 'BRK.B', name: 'Berkshire Hathaway (Class B)', koreanName: '버크셔 해서웨이 B', industry: '지주사/보험/투자', targetPe: 18 },
  { country: 'US', ticker: 'JPM', name: 'JPMorgan Chase & Co.', koreanName: 'JP모건 체이스', industry: '글로벌투자은행', targetPe: 13 },
  { country: 'US', ticker: 'V', name: 'Visa Inc.', koreanName: '비자', industry: '글로벌결제네트워크', targetPe: 28 },
  { country: 'US', ticker: 'MA', name: 'Mastercard Incorporated', koreanName: '마스터카드', industry: '글로벌결제네트워크', targetPe: 30 },
  { country: 'US', ticker: 'BAC', name: 'Bank of America Corp.', koreanName: '뱅크오브아메리카', industry: '상업은행/금융', targetPe: 12 },
  { country: 'US', ticker: 'WFC', name: 'Wells Fargo & Company', koreanName: '웰스파고', industry: '상업은행/금융', targetPe: 12 },
  { country: 'US', ticker: 'MS', name: 'Morgan Stanley', koreanName: '모건스탠리', industry: '투자은행/자산관리', targetPe: 15 },
  { country: 'US', ticker: 'GS', name: 'The Goldman Sachs Group', koreanName: '골드만삭스', industry: '투자은행/증권', targetPe: 14 },
  { country: 'US', ticker: 'BLK', name: 'BlackRock Inc.', koreanName: '블랙록', industry: '글로벌자산운용', targetPe: 22 },
  { country: 'US', ticker: 'SCHW', name: 'Charles Schwab Corp.', koreanName: '찰스 슈왑', industry: '온라인증권/금융', targetPe: 20 },
  { country: 'US', ticker: 'AXP', name: 'American Express Company', koreanName: '아메리칸 익스프레스', industry: '신용카드/결제', targetPe: 18 },
  { country: 'US', ticker: 'C', name: 'Citigroup Inc.', koreanName: '씨티그룹', industry: '글로벌은행', targetPe: 10 },
  { country: 'US', ticker: 'SPGI', name: 'S&P Global Inc.', koreanName: 'S&P 글로벌', industry: '신용평가/금융데이터', targetPe: 30 },
  { country: 'US', ticker: 'MCO', name: 'Moody\'s Corporation', koreanName: '무디스', industry: '신용평가/금융데이터', targetPe: 32 },
  { country: 'US', ticker: 'PYPL', name: 'PayPal Holdings', koreanName: '페이팔', industry: '디지털결제/핀테크', targetPe: 16 },
  { country: 'US', ticker: 'SQ', name: 'Block Inc. (Square)', koreanName: '블록 (스퀘어)', industry: '디지털결제/비트코인', targetPe: 25 },
  { country: 'US', ticker: 'COIN', name: 'Coinbase Global Inc.', koreanName: '코인베이스', industry: '가상자산거래소', targetPe: 30 },
  { country: 'US', ticker: 'HOOD', name: 'Robinhood Markets', koreanName: '로빈후드', industry: '핀테크증권', targetPe: 25 },

  // Consumer, Retail, Entertainment
  { country: 'US', ticker: 'WMT', name: 'Walmart Inc.', koreanName: '월마트', industry: '대형유통/이커머스', targetPe: 26 },
  { country: 'US', ticker: 'COST', name: 'Costco Wholesale Corp.', koreanName: '코스트코', industry: '회원제유통', targetPe: 40 },
  { country: 'US', ticker: 'PG', name: 'Procter & Gamble Co.', koreanName: '프록터 앤 갬블 (P&G)', industry: '생활용품/소비재', targetPe: 24 },
  { country: 'US', ticker: 'HD', name: 'The Home Depot Inc.', koreanName: '홈디포', industry: '주택개선유통', targetPe: 22 },
  { country: 'US', ticker: 'KO', name: 'The Coca-Cola Company', koreanName: '코카콜라', industry: '음료/식품', targetPe: 23 },
  { country: 'US', ticker: 'PEP', name: 'PepsiCo Inc.', koreanName: '펩시코', industry: '음료/스낵', targetPe: 21 },
  { country: 'US', ticker: 'MCD', name: 'McDonald\'s Corporation', koreanName: '맥도날드', industry: '패스트푸드프랜차이즈', targetPe: 24 },
  { country: 'US', ticker: 'NKE', name: 'Nike Inc.', koreanName: '나이키', industry: '스포츠의류/신발', targetPe: 25 },
  { country: 'US', ticker: 'SBUX', name: 'Starbucks Corporation', koreanName: '스타벅스', industry: '커피/외식', targetPe: 24 },
  { country: 'US', ticker: 'TGT', name: 'Target Corporation', koreanName: '타겟', industry: '대형할인점', targetPe: 15 },
  { country: 'US', ticker: 'LOW', name: 'Lowe\'s Companies', koreanName: '로우스', industry: '주택개선유통', targetPe: 18 },
  { country: 'US', ticker: 'PM', name: 'Philip Morris International', koreanName: '필립모리스', industry: '담배/소비재', targetPe: 17 },
  { country: 'US', ticker: 'MO', name: 'Altria Group Inc.', koreanName: '알트리아', industry: '담배/소비재', targetPe: 10 },
  { country: 'US', ticker: 'CL', name: 'Colgate-Palmolive', koreanName: '콜게이트', industry: '구강케어/생활용품', targetPe: 25 },
  { country: 'US', ticker: 'MDLZ', name: 'Mondelez International', koreanName: '몬델리즈', industry: '제과/스낵', targetPe: 20 },
  { country: 'US', ticker: 'EL', name: 'The Estée Lauder Companies', koreanName: '에스티로더', industry: '화장품/뷰티', targetPe: 25 },
  { country: 'US', ticker: 'DIS', name: 'The Walt Disney Company', koreanName: '디즈니', industry: '엔터테인먼트/미디어', targetPe: 22 },
  { country: 'US', ticker: 'NFLX', name: 'Netflix Inc.', koreanName: '넷플릭스', industry: 'OTT스트리밍', targetPe: 35 },
  { country: 'US', ticker: 'CMCSA', name: 'Comcast Corporation', koreanName: '컴캐스트', industry: '미디어/통신', targetPe: 12 },
  { country: 'US', ticker: 'SPOT', name: 'Spotify Technology S.A.', koreanName: '스포티파이', industry: '음악스트리밍', targetPe: 40 },
  { country: 'US', ticker: 'UBER', name: 'Uber Technologies', koreanName: '우버', industry: '모빌리티/배달', targetPe: 30 },
  { country: 'US', ticker: 'ABNB', name: 'Airbnb Inc.', koreanName: '에어비앤비', industry: '숙박공유/여행', targetPe: 28 },
  { country: 'US', ticker: 'BKNG', name: 'Booking Holdings Inc.', koreanName: '부킹홀딩스 (아고다)', industry: '온라인여행예약', targetPe: 24 },

  // Industrials, Energy, Defense & Telecom
  { country: 'US', ticker: 'XOM', name: 'Exxon Mobil Corporation', koreanName: '엑슨모빌', industry: '석유/에너지', targetPe: 13 },
  { country: 'US', ticker: 'CVX', name: 'Chevron Corporation', koreanName: '셰브론', industry: '석유/에너지', targetPe: 13 },
  { country: 'US', ticker: 'COP', name: 'ConocoPhillips', koreanName: '코노코필립스', industry: '석유가스탐사/생산', targetPe: 12 },
  { country: 'US', ticker: 'SLB', name: 'Schlumberger Limited (SLB)', koreanName: '슐룸베르거', industry: '에너지서비스/유전장비', targetPe: 15 },
  { country: 'US', ticker: 'CAT', name: 'Caterpillar Inc.', koreanName: '캐터필러', industry: '건설/광산기계', targetPe: 17 },
  { country: 'US', ticker: 'DE', name: 'Deere & Company', koreanName: '디어 (존디어)', industry: '농기계/중장비', targetPe: 15 },
  { country: 'US', ticker: 'GE', name: 'GE Aerospace', koreanName: 'GE 에어로스페이스', industry: '항공엔진/방위산업', targetPe: 30 },
  { country: 'US', ticker: 'LMT', name: 'Lockheed Martin Corp.', koreanName: '록히드마틴', industry: '방위산업/항공우주', targetPe: 18 },
  { country: 'US', ticker: 'RTX', name: 'RTX Corporation', koreanName: '레이시온 테크놀로지스', industry: '항공우주/방위산업', targetPe: 20 },
  { country: 'US', ticker: 'BA', name: 'The Boeing Company', koreanName: '보잉', industry: '민항기/방위산업', targetPe: 20 },
  { country: 'US', ticker: 'HON', name: 'Honeywell International', koreanName: '허니웰', industry: '복합산업/항공엔지니어링', targetPe: 20 },
  { country: 'US', ticker: 'UNP', name: 'Union Pacific Corporation', koreanName: '유니온퍼시픽', industry: '철도물류', targetPe: 20 },
  { country: 'US', ticker: 'NEE', name: 'NextEra Energy', koreanName: '넥스트에라 에너지', industry: '신재생에너지/전력', targetPe: 22 },
  { country: 'US', ticker: 'T', name: 'AT&T Inc.', koreanName: 'AT&T', industry: '통신서비스', targetPe: 9 },
  { country: 'US', ticker: 'VZ', name: 'Verizon Communications', koreanName: '버라이즌', industry: '통신서비스', targetPe: 10 },
  { country: 'US', ticker: 'TMUS', name: 'T-Mobile US Inc.', koreanName: 'T모바일', industry: '무선통신', targetPe: 20 },
  // Additional US High Growth / Popular Leaders
  { country: 'US', ticker: 'SMCI', name: 'Super Micro Computer Inc.', koreanName: '슈퍼마이크로컴퓨터', industry: 'AI서버/하드웨어', targetPe: 25 },
  { country: 'US', ticker: 'DELL', name: 'Dell Technologies Inc.', koreanName: '델 테크놀로지스', industry: 'AI서버/PC', targetPe: 16 },
  { country: 'US', ticker: 'HPQ', name: 'HP Inc.', koreanName: 'HP', industry: 'PC/프린팅', targetPe: 11 },
  { country: 'US', ticker: 'ANET', name: 'Arista Networks', koreanName: '아리스타 네트웍스', industry: 'AI데이터센터네트워크', targetPe: 35 },
  { country: 'US', ticker: 'MSTR', name: 'MicroStrategy Inc.', koreanName: '마이크로스트래티지 (비트코인보유)', industry: '비트코인/소프트웨어', targetPe: 40 },
  { country: 'US', ticker: 'MARA', name: 'MARA Holdings Inc.', koreanName: '마라톤 디지털 (채굴)', industry: '비트코인채굴', targetPe: 25 },
  { country: 'US', ticker: 'RIOT', name: 'Riot Platforms', koreanName: '라이엇 플랫폼', industry: '비트코인채굴', targetPe: 25 },
  { country: 'US', ticker: 'RIVN', name: 'Rivian Automotive', koreanName: '리비안', industry: '전기차(EV)', targetPe: 25 },
  { country: 'US', ticker: 'LCID', name: 'Lucid Group Inc.', koreanName: '루시드', industry: '전기차(EV)', targetPe: 25 },
  { country: 'US', ticker: 'SOFI', name: 'SoFi Technologies', koreanName: '소파이 테크놀로지스', industry: '핀테크/네오뱅크', targetPe: 25 },
  { country: 'US', ticker: 'UPST', name: 'Upstart Holdings', koreanName: '업스타트', industry: 'AI대출플랫폼', targetPe: 30 },
  { country: 'US', ticker: 'AFRM', name: 'Affirm Holdings', koreanName: '어펌 홀딩스 (BNPL)', industry: '선구매후결제(BNPL)', targetPe: 30 },
  { country: 'US', ticker: 'SNOW', name: 'Snowflake Inc.', koreanName: '스노우플레이크', industry: '클라우드데이터웨어하우스', targetPe: 40 },
  { country: 'US', ticker: 'DDOG', name: 'Datadog Inc.', koreanName: '데이터독', industry: '클라우드모니터링/보안', targetPe: 40 },
  { country: 'US', ticker: 'NET', name: 'Cloudflare Inc.', koreanName: '클라우드플레어', industry: 'CDN/엣지컴퓨팅/보안', targetPe: 45 },
  { country: 'US', ticker: 'ZS', name: 'Zscaler Inc.', koreanName: '지스케일러', industry: '제로트러스트보안', targetPe: 45 },
  { country: 'US', ticker: 'PATH', name: 'UiPath Inc.', koreanName: '유아이패스', industry: 'RPA/업무자동화', targetPe: 25 },
  { country: 'US', ticker: 'IONQ', name: 'IonQ Inc.', koreanName: '아이온큐', industry: '양자컴퓨팅', targetPe: 50 },
  { country: 'US', ticker: 'RGTI', name: 'Rigetti Computing', koreanName: '리게티 컴퓨팅', industry: '양자컴퓨팅', targetPe: 40 },
  { country: 'US', ticker: 'QBTS', name: 'D-Wave Quantum', koreanName: '디웨이브 퀀텀', industry: '양자컴퓨팅', targetPe: 40 },
  { country: 'US', ticker: 'RKLB', name: 'Rocket Lab USA', koreanName: '로켓랩', industry: '우주발사체/위성', targetPe: 35 },
  { country: 'US', ticker: 'ASTS', name: 'AST SpaceMobile', koreanName: 'AST 스페이스모바일', industry: '우주위성통신', targetPe: 40 },
  { country: 'US', ticker: 'LUNR', name: 'Intuitive Machines', koreanName: '인튜이티브 머신스', industry: '달탐사/우주인프라', targetPe: 30 },
  { country: 'US', ticker: 'SPCE', name: 'Virgin Galactic', koreanName: '버진 갤럭틱', industry: '우주관광', targetPe: 25 },
  { country: 'US', ticker: 'JOBY', name: 'Joby Aviation', koreanName: '조비 에비에이션 (UAM)', industry: '도심항공교통(UAM)', targetPe: 35 },
  { country: 'US', ticker: 'ACHR', name: 'Archer Aviation', koreanName: '아처 에비에이션 (UAM)', industry: '도심항공교통(UAM)', targetPe: 35 },
  { country: 'US', ticker: 'DNA', name: 'Ginkgo Bioworks', koreanName: '징코 바이오웍스', industry: '합성생물학', targetPe: 25 },
  { country: 'US', ticker: 'CRSP', name: 'CRISPR Therapeutics', koreanName: '크리스퍼 테라퓨틱스', industry: '유전자편집치료', targetPe: 35 }
];

// 2. VIETNAM (VN) - Top 160+ VN100, HNX30 & Liquidity Leaders
const vnStocks = [
  // Banking & Financial Services (25)
  { country: 'VN', ticker: 'VCB', name: 'Vietcombank', koreanName: '비엣콤뱅크', industry: '국영상업은행', targetPe: 15 },
  { country: 'VN', ticker: 'BID', name: 'BIDV Bank', koreanName: 'BIDV 은행', industry: '국영상업은행', targetPe: 13 },
  { country: 'VN', ticker: 'CTG', name: 'VietinBank', koreanName: '비에틴뱅크', industry: '국영은행', targetPe: 9 },
  { country: 'VN', ticker: 'TCB', name: 'Techcombank', koreanName: '테크콤뱅크', industry: '민간상업은행', targetPe: 8 },
  { country: 'VN', ticker: 'MBB', name: 'Military Commercial Bank', koreanName: 'MB은행 (군대은행)', industry: '은행/금융', targetPe: 7 },
  { country: 'VN', ticker: 'VPB', name: 'VPBank', koreanName: 'VP은행', industry: '디지털금융/소비자금융', targetPe: 8 },
  { country: 'VN', ticker: 'ACB', name: 'Asia Commercial Bank', koreanName: '아시아상업은행 (ACB)', industry: '우량소매은행', targetPe: 7 },
  { country: 'VN', ticker: 'HDB', name: 'HDBank', koreanName: 'HD은행', industry: '은행/금융', targetPe: 7 },
  { country: 'VN', ticker: 'STB', name: 'Sacombank', koreanName: '사콤뱅크', industry: '은행/금융', targetPe: 8 },
  { country: 'VN', ticker: 'TPB', name: 'Tien Phong Bank', koreanName: '티엔퐁뱅크 (TPBank)', industry: '디지털은행', targetPe: 8 },
  { country: 'VN', ticker: 'VIB', name: 'Vietnam International Bank', koreanName: '베트남국제은행 (VIB)', industry: '소매금융/오토론', targetPe: 7 },
  { country: 'VN', ticker: 'LPB', name: 'LPBank (LienVietPostBank)', koreanName: '록팟은행 (LPBank)', industry: '은행/우체국망', targetPe: 8 },
  { country: 'VN', ticker: 'SHB', name: 'Saigon - Hanoi Bank', koreanName: 'SHB 은행', industry: '상업은행', targetPe: 7 },
  { country: 'VN', ticker: 'SSB', name: 'SeABank', koreanName: '세아은행', industry: '은행/금융', targetPe: 8 },
  { country: 'VN', ticker: 'MSB', name: 'Maritime Bank (MSB)', koreanName: 'MSB 은행 (해양은행)', industry: '디지털상업은행', targetPe: 7 },
  { country: 'VN', ticker: 'OCB', name: 'Orient Commercial Bank', koreanName: 'OCB 은행 (동양은행)', industry: '소매금융/중소기업', targetPe: 7 },
  { country: 'VN', ticker: 'EIB', name: 'Eximbank Vietnam', koreanName: '수출입은행 (엑심뱅크)', industry: '무역금융/상업은행', targetPe: 10 },
  { country: 'VN', ticker: 'NAB', name: 'Nam A Bank', koreanName: '남아은행', industry: '소매상업은행', targetPe: 7 },
  { country: 'VN', ticker: 'ABB', name: 'An Binh Bank (ABBank)', koreanName: '안빈은행', industry: '상업은행/전력금융', targetPe: 8 },
  { country: 'VN', ticker: 'BAB', name: 'Bac A Bank', koreanName: '북아은행', industry: '상업은행/농업투자', targetPe: 10 },
  { country: 'VN', ticker: 'BVB', name: 'BVBank (Viet Capital Bank)', koreanName: '비엣캐피탈은행 (BVBank)', industry: '디지털은행', targetPe: 8 },
  { country: 'VN', ticker: 'NVB', name: 'National Citizen Bank (NCB)', koreanName: 'NCB 은행', industry: '상업은행', targetPe: 10 },
  { country: 'VN', ticker: 'VBB', name: 'VietBank', koreanName: '비엣뱅크', industry: '상업은행', targetPe: 8 },
  { country: 'VN', ticker: 'BVH', name: 'Bao Viet Holdings', koreanName: '바오비엣 홀딩스', industry: '보험/금융', targetPe: 16 },
  { country: 'VN', ticker: 'BMI', name: 'Bao Minh Insurance', koreanName: '바오민보험', industry: '손해보험', targetPe: 12 },

  // Securities & Investment (16)
  { country: 'VN', ticker: 'SSI', name: 'SSI Securities Corp', koreanName: 'SSI 증권', industry: '증권/투자', targetPe: 15 },
  { country: 'VN', ticker: 'VND', name: 'VNDIRECT Securities', koreanName: 'VNDIRECT 증권', industry: '온라인증권/핀테크', targetPe: 12 },
  { country: 'VN', ticker: 'VCI', name: 'Vietcap Securities', koreanName: '비엣캡 증권', industry: '투자은행/증권', targetPe: 16 },
  { country: 'VN', ticker: 'HCM', name: 'Ho Chi Minh City Securities (HSC)', koreanName: 'HSC 증권', industry: '증권/중개', targetPe: 14 },
  { country: 'VN', ticker: 'SHS', name: 'Saigon-Hanoi Securities', koreanName: 'SHS 증권', industry: '종합증권', targetPe: 12 },
  { country: 'VN', ticker: 'MBS', name: 'MB Securities', koreanName: 'MBS 증권 (군대증권)', industry: '증권/자산관리', targetPe: 14 },
  { country: 'VN', ticker: 'FTS', name: 'FPT Securities', koreanName: 'FPT 증권', industry: '핀테크/증권', targetPe: 15 },
  { country: 'VN', ticker: 'BSI', name: 'BIDV Securities', koreanName: 'BSC 증권', industry: '증권/IB', targetPe: 14 },
  { country: 'VN', ticker: 'CTS', name: 'Vietinbank Securities', koreanName: '비에틴증권', industry: '증권/중개', targetPe: 12 },
  { country: 'VN', ticker: 'AGR', name: 'Agribank Securities (Agriseco)', koreanName: '아그리세코 증권', industry: '농협증권', targetPe: 12 },
  { country: 'VN', ticker: 'BVS', name: 'Bao Viet Securities', koreanName: '바오비엣 증권', industry: '증권/자산관리', targetPe: 12 },
  { country: 'VN', ticker: 'VIX', name: 'VIX Securities Corp', koreanName: 'VIX 증권', industry: '자기자본투자/증권', targetPe: 12 },
  { country: 'VN', ticker: 'ORS', name: 'Tien Phong Securities (TPS)', koreanName: 'TPS 증권 (티엔퐁증권)', industry: '채권/IB증권', targetPe: 11 },
  { country: 'VN', ticker: 'TVS', name: 'Thien Viet Securities', koreanName: '티엔비엣 증권', industry: '사모투자/IB', targetPe: 14 },
  { country: 'VN', ticker: 'VDS', name: 'Viet Dragon Securities (VDSC)', koreanName: '비엣드래곤 증권', industry: '중개/투자자문', targetPe: 12 },
  { country: 'VN', ticker: 'EVS', name: 'Everest Securities', koreanName: '에베레스트 증권', industry: '증권중개', targetPe: 11 },

  // Real Estate & Industrial Park Development (28)
  { country: 'VN', ticker: 'VIC', name: 'Vingroup JSC', koreanName: '빈그룹', industry: '지주사/복합기업', targetPe: 20 },
  { country: 'VN', ticker: 'VHM', name: 'Vinhomes JSC', koreanName: '빈홈즈', industry: '부동산개발', targetPe: 12 },
  { country: 'VN', ticker: 'VRE', name: 'Vincom Retail JSC', koreanName: '빈콤리테일', industry: '쇼핑몰/상업용부동산', targetPe: 14 },
  { country: 'VN', ticker: 'NVL', name: 'Novaland Group', koreanName: '노바랜드', industry: '주거용부동산개발', targetPe: 15 },
  { country: 'VN', ticker: 'PDR', name: 'Phat Dat Real Estate', koreanName: '팟닷부동산개발', industry: '부동산개발', targetPe: 15 },
  { country: 'VN', ticker: 'KDH', name: 'Khang Dien House', koreanName: '캉디엔하우스', industry: '주거용부동산', targetPe: 16 },
  { country: 'VN', ticker: 'DIG', name: 'DIC Corp', koreanName: 'DIC 코퍼레이션', industry: '도시개발/리조트', targetPe: 20 },
  { country: 'VN', ticker: 'DXG', name: 'Dat Xanh Group', koreanName: '닷싼그룹', industry: '부동산중개/개발', targetPe: 16 },
  { country: 'VN', ticker: 'NLG', name: 'Nam Long Investment', koreanName: '남롱 투자', industry: '주거용부동산개발', targetPe: 15 },
  { country: 'VN', ticker: 'KBC', name: 'Kinh Bac City Development', koreanName: '킨박도시개발', industry: '산업단지/부동산', targetPe: 15 },
  { country: 'VN', ticker: 'BCM', name: 'Becamex IDC Corp', koreanName: '베카멕스 IDC', industry: '산업단지개발', targetPe: 20 },
  { country: 'VN', ticker: 'CEO', name: 'C.E.O Group', koreanName: 'CEO 그룹', industry: '리조트/부동산개발', targetPe: 18 },
  { country: 'VN', ticker: 'IDC', name: 'IDICO Corporation', koreanName: '이디코 (IDICO)', industry: '산업단지인프라', targetPe: 14 },
  { country: 'VN', ticker: 'SZC', name: 'Sonadezi Chau Duc', koreanName: '소나데지 차우득', industry: '산업단지/도시개발', targetPe: 14 },
  { country: 'VN', ticker: 'VGC', name: 'Viglacera Corporation', koreanName: '비글라세라', industry: '산업단지/건축자재', targetPe: 15 },
  { country: 'VN', ticker: 'HDG', name: 'Ha Do Group', koreanName: '하도그룹', industry: '신재생에너지/부동산', targetPe: 13 },
  { country: 'VN', ticker: 'TCH', name: 'Hoang Huy Investment Financial', koreanName: '황후이 투자금융', industry: '부동산/트럭유통', targetPe: 11 },
  { country: 'VN', ticker: 'CII', name: 'HCMC Infrastructure Investment', koreanName: '호치민 인프라투자 (CII)', industry: '도로인프라/부동산', targetPe: 14 },
  { country: 'VN', ticker: 'BCG', name: 'Bamboo Capital Group', koreanName: '밤부캐피탈', industry: '신재생에너지/부동산', targetPe: 12 },
  { country: 'VN', ticker: 'DXS', name: 'Dat Xanh Real Estate Services', koreanName: '닷싼 서비스', industry: '부동산유통/중개', targetPe: 14 },
  { country: 'VN', ticker: 'SCR', name: 'TTC Land', koreanName: 'TTC 랜드', industry: '부동산개발', targetPe: 14 },
  { country: 'VN', ticker: 'IJC', name: 'Becamex IJC', koreanName: '베카멕스 IJC', industry: '유료도로/부동산', targetPe: 12 },
  { country: 'VN', ticker: 'HUT', name: 'Tasco JSC', koreanName: '타스코 (HUT)', industry: '스마트교통/인프라/부동산', targetPe: 16 },
  { country: 'VN', ticker: 'AGG', name: 'An Gia Real Estate', koreanName: '안지아 부동산', industry: '아파트개발', targetPe: 12 },
  { country: 'VN', ticker: 'DPG', name: 'Dat Phuong Group', koreanName: '닷프엉 그룹', industry: '교량건설/수력/부동산', targetPe: 12 },
  { country: 'VN', ticker: 'CRE', name: 'Century Land (CenLand)', koreanName: '센랜드 (센그룹)', industry: '부동산프롭테크', targetPe: 14 },
  { country: 'VN', ticker: 'NBB', name: '577 Investment Corp', koreanName: '577 투자', industry: '인프라/주거개발', targetPe: 14 },
  { country: 'VN', ticker: 'QCG', name: 'Quoc Cuong Gia Lai', koreanName: '꾸옥끄엉 잘라이', industry: '부동산/고무', targetPe: 15 },

  // Steel, Metals & Construction Materials (12)
  { country: 'VN', ticker: 'HPG', name: 'Hoa Phat Group', koreanName: '화팟그룹', industry: '철강/제조', targetPe: 14 },
  { country: 'VN', ticker: 'HSG', name: 'Hoa Sen Group', koreanName: '호아센그룹', industry: '아연도금강판/파이프', targetPe: 13 },
  { country: 'VN', ticker: 'NKG', name: 'Nam Kim Steel', koreanName: '남킴스틸', industry: '도금강판수출', targetPe: 12 },
  { country: 'VN', ticker: 'VGS', name: 'Vietnam Germany Steel Pipe', koreanName: '베트남-독일 강관 (VGS)', industry: '강관제조/부동산', targetPe: 13 },
  { country: 'VN', ticker: 'TLH', name: 'Tien Len Steel', koreanName: '띠엔렌 철강', industry: '철강유통', targetPe: 10 },
  { country: 'VN', ticker: 'TVN', name: 'VNSTEEL (Vietnam Steel Corp)', koreanName: '베트남국영철강총공사', industry: '국영철강', targetPe: 10 },
  { country: 'VN', ticker: 'HT1', name: 'Ha Tien 1 Cement', koreanName: '하띠엔 1 시멘트', industry: '시멘트/건축자재', targetPe: 12 },
  { country: 'VN', ticker: 'BCC', name: 'Bim Son Cement', koreanName: '빔손 시멘트', industry: '시멘트제조', targetPe: 12 },
  { country: 'VN', ticker: 'VCS', name: 'Vicostone JSC', koreanName: '비코스톤 (인조대리석)', industry: '고급엔지니어드스톤', targetPe: 12 },
  { country: 'VN', ticker: 'BMP', name: 'Binh Minh Plastics', koreanName: '빈민플라스틱 (PVC파이프)', industry: '건축용플라스틱배관', targetPe: 11 },
  { country: 'VN', ticker: 'NTP', name: 'Tien Phong Plastics', koreanName: '띠엔퐁플라스틱', industry: '플라스틱파이프', targetPe: 11 },
  { country: 'VN', ticker: 'PTB', name: 'Phu Tai JSC', koreanName: '푸타이 (석재/가구/도요타딜러)', industry: '화강석가공/원목가구', targetPe: 11 },

  // IT, Telecom & Tech (8)
  { country: 'VN', ticker: 'FPT', name: 'FPT Corporation', koreanName: 'FPT 코퍼레이션', industry: 'IT서비스/소프트웨어', targetPe: 22 },
  { country: 'VN', ticker: 'CMG', name: 'CMC Corporation', koreanName: 'CMC 코퍼레이션', industry: '클라우드/데이터센터/IT', targetPe: 20 },
  { country: 'VN', ticker: 'ELC', name: 'Elcom Corp', koreanName: '엘콤 (Elcom)', industry: '지능형교통(ITS)/통신SW', targetPe: 18 },
  { country: 'VN', ticker: 'FOX', name: 'FPT Telecom', koreanName: 'FPT 텔레콤', industry: '초고속인터넷/IPTV', targetPe: 16 },
  { country: 'VN', ticker: 'CTR', name: 'Viettel Construction', koreanName: '비엣텔 건설 (통신타워)', industry: '5G인프라구축/타워임대', targetPe: 20 },
  { country: 'VN', ticker: 'VGI', name: 'Viettel Global', koreanName: '비엣텔 글로벌', industry: '해외이동통신망운영', targetPe: 22 },
  { country: 'VN', ticker: 'SAM', name: 'SAM Holdings', koreanName: 'SAM 홀딩스', industry: '통신케이블/투자', targetPe: 15 },
  { country: 'VN', ticker: 'ITD', name: 'Innovative Technology Development', koreanName: 'ITD 코퍼레이션', industry: '자동통행료징수(ETC)/IT', targetPe: 15 },

  // Energy, Oil & Gas, Utilities (18)
  { country: 'VN', ticker: 'GAS', name: 'PV GAS (PetroVietnam Gas)', koreanName: '페트로베트남 가스', industry: '천연가스/에너지', targetPe: 15 },
  { country: 'VN', ticker: 'PLX', name: 'Petrolimex', koreanName: '페트로리멕스', industry: '석유유통', targetPe: 16 },
  { country: 'VN', ticker: 'POW', name: 'PetroVietnam Power Corp', koreanName: '페트로베트남 전력 (PV Power)', industry: '발전/전력', targetPe: 14 },
  { country: 'VN', ticker: 'PVD', name: 'Petrovietnam Drilling', koreanName: 'PV 드릴링', industry: '유전시추/해양플랜트', targetPe: 16 },
  { country: 'VN', ticker: 'PVS', name: 'PetroVietnam Technical Services', koreanName: 'PV 기술서비스', industry: '해상풍력/EPC', targetPe: 16 },
  { country: 'VN', ticker: 'PVT', name: 'PetroVietnam Transportation (PVTrans)', koreanName: 'PV 트랜스 (유조선운송)', industry: '원유/LPG해상운송', targetPe: 11 },
  { country: 'VN', ticker: 'BSR', name: 'Binh Son Refining and Petrochemical', koreanName: '빈손정유화학 (BSR)', industry: '정유/석유화학', targetPe: 10 },
  { country: 'VN', ticker: 'OIL', name: 'PV OIL (PetroVietnam Oil)', koreanName: 'PV 오일', industry: '석유주유소유통', targetPe: 14 },
  { country: 'VN', ticker: 'NT2', name: 'Nhon Trach 2 Petroleum Power', koreanName: '년짝2 화력발전', industry: '가스터빈복합화력', targetPe: 13 },
  { country: 'VN', ticker: 'PGV', name: 'EVNGENCO3', koreanName: 'EVN 3발전공사', industry: '대형국영발전사', targetPe: 12 },
  { country: 'VN', ticker: 'GEG', name: 'Gia Lai Electricity', koreanName: '잘라이 전력 (GEC)', industry: '태양광/풍력/수력발전', targetPe: 14 },
  { country: 'VN', ticker: 'PC1', name: 'PC1 Group', koreanName: 'PC1 그룹 (전력설비1공사)', industry: '송배전EPC/풍력발전/니켈', targetPe: 15 },
  { country: 'VN', ticker: 'REE', name: 'REE Corporation', koreanName: '냉전기엔지니어링 (REE)', industry: '신재생발전/인프라', targetPe: 12 },
  { country: 'VN', ticker: 'PPC', name: 'Pha Lai Thermal Power', koreanName: '파라이 화력발전', industry: '석탄화력발전', targetPe: 11 },
  { country: 'VN', ticker: 'VSH', name: 'Vinh Son - Song Hinh Hydropower', koreanName: '빈손-송힌 수력발전', industry: '대형수력발전', targetPe: 11 },
  { country: 'VN', ticker: 'QTP', name: 'Quang Ninh Thermal Power', koreanName: '꽝닌 화력발전', industry: '화력발전/고배당', targetPe: 10 },
  { country: 'VN', ticker: 'HND', name: 'Hai Phong Thermal Power', koreanName: '하이퐁 화력발전', industry: '화력발전/고배당', targetPe: 10 },
  { country: 'VN', ticker: 'TTA', name: 'Truong Thanh Energy and Real Estate', koreanName: '쯔엉탄 에너지', industry: '태양광/수력발전', targetPe: 13 },

  // Food, Beverage & Agriculture (14)
  { country: 'VN', ticker: 'VNM', name: 'Vietnam Dairy Products (Vinamilk)', koreanName: '비나밀크', industry: '음식료', targetPe: 16 },
  { country: 'VN', ticker: 'MSN', name: 'Masan Group', koreanName: '마산그룹', industry: '소비재/유통', targetPe: 18 },
  { country: 'VN', ticker: 'SAB', name: 'Sabeco (Saigon Beer)', koreanName: '사베코 (사이공맥주)', industry: '주류/맥주', targetPe: 18 },
  { country: 'VN', ticker: 'KDC', name: 'KIDO Group', koreanName: '키도그룹', industry: '식용유/제과/아이스크림', targetPe: 16 },
  { country: 'VN', ticker: 'QNS', name: 'Quang Ngai Sugar', koreanName: '꽝응아이 설탕 (비타소이)', industry: '두유음료/설탕', targetPe: 11 },
  { country: 'VN', ticker: 'DBC', name: 'Dabaco Group', koreanName: '다바코 그룹', industry: '양돈/사료/백신', targetPe: 13 },
  { country: 'VN', ticker: 'BAF', name: 'BAF Vietnam Agriculture', koreanName: 'BAF 베트남 농업', industry: '클린돈육/3F사료', targetPe: 14 },
  { country: 'VN', ticker: 'HAG', name: 'Hoang Anh Gia Lai', koreanName: '황안잘라이 (HAGL)', industry: '바나나/두리안/돼지', targetPe: 12 },
  { country: 'VN', ticker: 'HNG', name: 'HAGL Agrico', koreanName: 'HAGL 아그리코', industry: '대규모과수농업', targetPe: 14 },
  { country: 'VN', ticker: 'MCH', name: 'Masan Consumer Corp', koreanName: '마산 컨슈머', industry: '소스/간편식/라면', targetPe: 18 },
  { country: 'VN', ticker: 'BHN', name: 'Habeco (Hanoi Beer)', koreanName: '하베코 (하노이맥주)', industry: '맥주제조', targetPe: 16 },
  { country: 'VN', ticker: 'PAN', name: 'The PAN Group', koreanName: '팬그룹 (PAN Group)', industry: '농산물/종자/수산식품', targetPe: 12 },
  { country: 'VN', ticker: 'SBT', name: 'TTC Sugar (Thanh Thanh Cong)', koreanName: 'TTC 슈가', industry: '사탕수수당제조', targetPe: 12 },
  { country: 'VN', ticker: 'LSS', name: 'Lam Son Sugar Cane', koreanName: '람손 설탕', industry: '설탕/농식품', targetPe: 11 },

  // Retail, E-Commerce & Jewelry (6)
  { country: 'VN', ticker: 'MWG', name: 'Mobile World Investment Corp', koreanName: '모바일월드 (MWG)', industry: '전자기기유통/소매', targetPe: 18 },
  { country: 'VN', ticker: 'PNJ', name: 'Phu Nhuan Jewelry', koreanName: 'PNJ (푸년주얼리)', industry: '귀금속/명품주얼리', targetPe: 16 },
  { country: 'VN', ticker: 'FRT', name: 'FPT Digital Retail (Long Chau)', koreanName: 'FPT 리테일 (롱쩌우약국)', industry: '의약품약국체인/IT유통', targetPe: 25 },
  { country: 'VN', ticker: 'DGW', name: 'Digiworld Corp', koreanName: '디지월드', industry: '샤오미/애플ICT공식총판', targetPe: 16 },
  { country: 'VN', ticker: 'PET', name: 'Petrosetco', koreanName: '페트로셋코 (애플유통)', industry: 'ICT기기총판/케이터링', targetPe: 13 },
  { country: 'VN', ticker: 'HAX', name: 'Hang Xanh Motors Service', koreanName: '항싼 모터스 (벤츠딜러)', industry: '메르세데스벤츠공식딜러', targetPe: 11 },

  // Chemicals, Fertilizer, Rubber (10)
  { country: 'VN', ticker: 'DGC', name: 'Duc Giang Chemicals', koreanName: '득장화학', industry: '황인/반도체화학', targetPe: 14 },
  { country: 'VN', ticker: 'GVR', name: 'Vietnam Rubber Group', koreanName: '베트남고무그룹', industry: '고무/산업단지', targetPe: 16 },
  { country: 'VN', ticker: 'DPM', name: 'PetroVietnam Fertilizer (Dam Phu My)', koreanName: '푸미비료', industry: '비료/화학', targetPe: 11 },
  { country: 'VN', ticker: 'DCM', name: 'PetroVietnam Ca Mau Fertilizer', koreanName: '까마우비료', industry: '비료/농업화학', targetPe: 11 },
  { country: 'VN', ticker: 'PHR', name: 'Phuoc Hoa Rubber', koreanName: '프억호아 고무', industry: '천연고무/산업단지전환', targetPe: 13 },
  { country: 'VN', ticker: 'DPR', name: 'Dong Phu Rubber', koreanName: '동푸 고무', industry: '천연고무생산', targetPe: 12 },
  { country: 'VN', ticker: 'BFC', name: 'Binh Dien Fertilizer', koreanName: '빈디엔 비료 (두가우 비료)', industry: 'NPK복합비료', targetPe: 10 },
  { country: 'VN', ticker: 'CSV', name: 'South Basic Chemicals', koreanName: '남부기초화학 (CSV)', industry: '가성소다/기초무기화학', targetPe: 12 },
  { country: 'VN', ticker: 'LAS', name: 'Lam Thao Fertilizers & Chemicals', koreanName: '람타오 비료화학', industry: '인산비료/과인산석회', targetPe: 11 },
  { country: 'VN', ticker: 'DRC', name: 'Danang Rubber JSC', koreanName: '다낭 고무 (DRC타이어)', industry: '트럭/버스레이디얼타이어', targetPe: 12 },

  // Seafood & Fishery (7)
  { country: 'VN', ticker: 'VHC', name: 'Vinh Hoan Corp', koreanName: '빈호안 (판가시우스 수산물)', industry: '수산물가공/수출', targetPe: 12 },
  { country: 'VN', ticker: 'ANV', name: 'Nam Viet Corp', koreanName: '남비엣', industry: '수산물/양식', targetPe: 12 },
  { country: 'VN', ticker: 'IDI', name: 'I.D.I International Development & Investment', koreanName: 'IDI 코퍼레이션', industry: '메기양식/생선기름', targetPe: 11 },
  { country: 'VN', ticker: 'FMC', name: 'Sao Ta Foods', koreanName: '사오타 푸드 (새우가공)', industry: '냉동새우수출', targetPe: 11 },
  { country: 'VN', ticker: 'MPC', name: 'Minh Phu Seafood', koreanName: '민푸 수산 (새우왕)', industry: '글로벌최대새우수출기업', targetPe: 12 },
  { country: 'VN', ticker: 'ACL', name: 'Cuu Long Fish', koreanName: '구룡 어류 (끄우롱)', industry: '메기필렛수출', targetPe: 10 },
  { country: 'VN', ticker: 'CMX', name: 'Camimex Group', koreanName: '카미멕스 그룹', industry: '유기농생태새우', targetPe: 11 },

  // Pharmaceuticals & Healthcare (7)
  { country: 'VN', ticker: 'DHG', name: 'DHG Pharmaceutical', koreanName: 'DHG 제약 (하우장제약)', industry: '베트남 1위 제약사', targetPe: 16 },
  { country: 'VN', ticker: 'IMP', name: 'Imexpharm Corp', koreanName: '이멕스팜 제약 (EU-GMP)', industry: '항생제/EU-GMP제약', targetPe: 18 },
  { country: 'VN', ticker: 'TRA', name: 'Traphaco JSC', koreanName: '트라파코 (전통한방의약)', industry: '천연물의약품/건기식', targetPe: 15 },
  { country: 'VN', ticker: 'DBD', name: 'Binh Dinh Pharmaceutical (Bidiphar)', koreanName: '비디파 제약', industry: '항암주사제/수액제', targetPe: 15 },
  { country: 'VN', ticker: 'DVN', name: 'Vietnam Pharmaceutical Corp (Vinapharm)', koreanName: '비나팜 (국영베트남제약총공사)', industry: '의약품유통/지주사', targetPe: 14 },
  { country: 'VN', ticker: 'DCL', name: 'Cuu Long Pharmaceutical', koreanName: '끄우롱 제약', industry: '캡슐/항생제', targetPe: 14 },
  { country: 'VN', ticker: 'OPC', name: 'OPC Pharmaceutical', koreanName: 'OPC 제약', industry: '한방의약품', targetPe: 13 },

  // Logistics, Marine Transportation & Ports (10)
  { country: 'VN', ticker: 'GMD', name: 'Gemadept Corp', koreanName: '제마뎁트 (Gemadept)', industry: '심해항만터미널/물류', targetPe: 16 },
  { country: 'VN', ticker: 'HAH', name: 'Hai An Transport and Stevedoring', koreanName: '하이안 운송하역', industry: '국내컨테이너선단/항만', targetPe: 11 },
  { country: 'VN', ticker: 'VSC', name: 'Vietnam Container Shipping (Viconship)', koreanName: '비콘쉽 (하이퐁컨테이너항)', industry: '컨테이너야드/항만하역', targetPe: 13 },
  { country: 'VN', ticker: 'VOS', name: 'Vietnam Ocean Shipping (Vosco)', koreanName: '보스코 (베트남해운)', industry: '벌크선/유조선해상운송', targetPe: 10 },
  { country: 'VN', ticker: 'PHP', name: 'Port of Hai Phong', koreanName: '하이퐁 항구', industry: '북부최대국영항만', targetPe: 13 },
  { country: 'VN', ticker: 'SGP', name: 'Saigon Port', koreanName: '사이공 항구', industry: '남부호치민항만운영', targetPe: 14 },
  { country: 'VN', ticker: 'TMS', name: 'Transimex Corp', koreanName: '트랜시멕스', industry: '종합물류/보세창고/ICD', targetPe: 11 },
  { country: 'VN', ticker: 'ILB', name: 'Interserco My Dinh', koreanName: '인터세르코 ICD', industry: '내륙물류기지/물류', targetPe: 12 },
  { country: 'VN', ticker: 'VIP', name: 'Viet Nam Petroleum Transport', koreanName: 'VIP 트랜스', industry: '석유해상운송', targetPe: 10 },
  { country: 'VN', ticker: 'VTO', name: 'Viet Nam Tanker JSC', koreanName: '비타코 (VITACO)', industry: '유조선운송/케미컬', targetPe: 10 },

  // Aviation, Tourism & Transportation (5)
  { country: 'VN', ticker: 'VJC', name: 'Vietjet Aviation', koreanName: '비엣젯항공', industry: '저비용항공(LCC)', targetPe: 18 },
  { country: 'VN', ticker: 'HVN', name: 'Vietnam Airlines', koreanName: '베트남항공 (국적기)', industry: '풀서비스국적항공사', targetPe: 15 },
  { country: 'VN', ticker: 'ACV', name: 'Airports Corporation of Vietnam', koreanName: '베트남공항공사 (ACV)', industry: '전국22개공항운영', targetPe: 22 },
  { country: 'VN', ticker: 'AST', name: 'Taseco Air Services', koreanName: '타세코 에어서비스', industry: '공항면세점/식음료라운지', targetPe: 16 },
  { country: 'VN', ticker: 'SKG', name: 'Superdong Fast Ferry Kien Giang', koreanName: '슈퍼동 고속선 (푸꾸옥페리)', industry: '해상여객고속선', targetPe: 12 },

  // Textile, Garment & Footwear (7)
  { country: 'VN', ticker: 'MSH', name: 'Song Hong Garment', koreanName: '송홍 의류 (나이키/콜롬비아OEM)', industry: '의류OEM수출', targetPe: 11 },
  { country: 'VN', ticker: 'TCM', name: 'Thanh Cong Textile Garment', koreanName: '타인꽁 섬유직물 (이랜드계열)', industry: '방적/염색/봉제일관', targetPe: 13 },
  { country: 'VN', ticker: 'TNG', name: 'TNG Investment and Trading', koreanName: 'TNG 투자무역 (데카트론OEM)', industry: '친환경의류수출', targetPe: 10 },
  { country: 'VN', ticker: 'GIL', name: 'Binh Thanh Import-Export (Gilimex)', koreanName: '길리멕스 (아마존보관함/산업단지)', industry: '섬유잡화/로봇산업단지', targetPe: 11 },
  { country: 'VN', ticker: 'STK', name: 'Century Synthetic Fiber', koreanName: '센추리 합성섬유', industry: '친환경리사이클원사', targetPe: 13 },
  { country: 'VN', ticker: 'VGT', name: 'Vietnam National Textile (Vinatex)', koreanName: '비나텍스 (베트남섬유의류총공사)', industry: '국영섬유그룹', targetPe: 12 },
  { country: 'VN', ticker: 'EVE', name: 'Everpia JSC', koreanName: '에버피아 (에버온 침구류)', industry: '침구류/패딩솜', targetPe: 11 }
];

// 3. CHINA (CN) - Top CSI 300 & A-Share Blue Chips
const cnStocks = [
  { country: 'CN', ticker: '600519', name: 'Kweichow Moutai', koreanName: '귀주모태주 (마오타이)', industry: '백주/프리미엄주류', targetPe: 25 },
  { country: 'CN', ticker: '000858', name: 'Wuliangye Yibin', koreanName: '오량액 (우량예)', industry: '백주/주류', targetPe: 20 },
  { country: 'CN', ticker: '601318', name: 'Ping An Insurance', koreanName: '중국평안보험', industry: '종합보험/금융', targetPe: 10 },
  { country: 'CN', ticker: '300750', name: 'CATL (Contemporary Amperex Technology)', koreanName: '닝더스다이 (CATL)', industry: '2차전지/배터리', targetPe: 25 },
  { country: 'CN', ticker: '002594', name: 'BYD Company Limited', koreanName: '비야디 (BYD)', industry: '전기차/배터리', targetPe: 24 },
  { country: 'CN', ticker: '601398', name: 'Industrial and Commercial Bank of China (ICBC)', koreanName: '중국공상은행 (ICBC)', industry: '국유상업은행', targetPe: 6 },
  { country: 'CN', ticker: '600036', name: 'China Merchants Bank', koreanName: '초상은행', industry: '소매금융/상업은행', targetPe: 8 },
  { country: 'CN', ticker: '600900', name: 'China Yangtze Power', koreanName: '양쯔전력 (장강전력)', industry: '수력발전/유틸리티', targetPe: 18 },
  { country: 'CN', ticker: '000333', name: 'Midea Group', koreanName: '메이디그룹 (미디어)', industry: '스마트가전/로봇', targetPe: 15 },
  { country: 'CN', ticker: '601857', name: 'PetroChina Company', koreanName: '페트로차이나 (중국석유)', industry: '석유천연가스', targetPe: 10 },
  { country: 'CN', ticker: '002415', name: 'Hangzhou Hikvision Digital Tech', koreanName: '하이크비전', industry: 'AI영상보안/CCTV', targetPe: 20 },
  { country: 'CN', ticker: '002475', name: 'Luxshare Precision Industry', koreanName: '럭스쉐어 정밀 (입신정밀)', industry: '정밀전자부품/애플공급사', targetPe: 22 },
  { country: 'CN', ticker: '000725', name: 'BOE Technology Group', koreanName: '징둥팡 (BOE)', industry: 'OLED/LCD디스플레이', targetPe: 16 },
  { country: 'CN', ticker: '600276', name: 'Jiangsu Hengrui Pharmaceuticals', koreanName: '항서제약', industry: '항암신약/바이오', targetPe: 32 },
  { country: 'CN', ticker: '600030', name: 'CITIC Securities', koreanName: '중신증권 (CITIC)', industry: '투자은행/종합증권', targetPe: 16 },
  { country: 'CN', ticker: '601288', name: 'Agricultural Bank of China', koreanName: '중국농업은행', industry: '대형국유은행', targetPe: 6 },
  { country: 'CN', ticker: '601988', name: 'Bank of China', koreanName: '중국은행', industry: '외환/글로벌은행', targetPe: 6 },
  { country: 'CN', ticker: '601939', name: 'China Construction Bank', koreanName: '중국건설은행', industry: '인프라금융/은행', targetPe: 6 },
  { country: 'CN', ticker: '600000', name: 'Shanghai Pudong Development Bank', koreanName: '상하이푸둥발전은행', industry: '상업은행', targetPe: 6 },
  { country: 'CN', ticker: '000001', name: 'Ping An Bank', koreanName: '평안은행', industry: '디지털소매은행', targetPe: 6 },
  { country: 'CN', ticker: '600309', name: 'Wanhua Chemical Group', koreanName: '만화화학', industry: 'MDI/특수화학', targetPe: 14 },
  { country: 'CN', ticker: '002714', name: 'Muyuan Foods', koreanName: '목원식품', industry: '스마트축산/양돈', targetPe: 14 },
  { country: 'CN', ticker: '300059', name: 'East Money Information', koreanName: '동방재부', industry: '온라인금융플랫폼/증권', targetPe: 28 },
  { country: 'CN', ticker: '601088', name: 'China Shenhua Energy', koreanName: '중국신화에너지', industry: '석탄/전력인프라', targetPe: 11 },
  { country: 'CN', ticker: '600887', name: 'Inner Mongolia Yili Industrial', koreanName: '이리유업 (이리홀딩스)', industry: '유제품/음식료', targetPe: 16 },
  { country: 'CN', ticker: '601888', name: 'China Tourism Group Duty Free', koreanName: '중국중면 (중국면세점)', industry: '면세점/관광유통', targetPe: 22 },
  { country: 'CN', ticker: '000651', name: 'Gree Electric Appliances', koreanName: '격력전기 (그리)', industry: '에어컨/스마트홈가전', targetPe: 10 },
  { country: 'CN', ticker: '601166', name: 'Industrial Bank', koreanName: '흥업은행', industry: '녹색금융/상업은행', targetPe: 6 },
  { country: 'CN', ticker: '600050', name: 'China United Network (China Unicom)', koreanName: '차이나유니콤 (중국연통)', industry: '5G통신/빅데이터', targetPe: 15 },
  { country: 'CN', ticker: '601728', name: 'China Telecom', koreanName: '차이나텔레콤 (중국전신)', industry: '통신/클라우드', targetPe: 15 },
  { country: 'CN', ticker: '600941', name: 'China Mobile', koreanName: '차이나모바일 (중국이동)', industry: '글로벌최대통신사', targetPe: 15 },
  { country: 'CN', ticker: '601899', name: 'Zijin Mining Group', koreanName: '자진광업', industry: '금/구리/리튬광산', targetPe: 16 },
  { country: 'CN', ticker: '601012', name: 'LONGi Green Energy Technology', koreanName: '융기실리콘 (론지)', industry: '태양광웨이퍼/모듈', targetPe: 16 },
  { country: 'CN', ticker: '300124', name: 'Shenzhen Inovance Technology', koreanName: '후이촨기술 (이노반스)', industry: '공장자동화/스마트제조', targetPe: 26 },
  { country: 'CN', ticker: '002460', name: 'Ganfeng Lithium', koreanName: '간펑리튬', industry: '수산화리튬/원자재', targetPe: 16 },
  { country: 'CN', ticker: '002466', name: 'Tianqi Lithium', koreanName: '천제리튬', industry: '리튬소재/광산', targetPe: 16 },
  { country: 'CN', ticker: '300760', name: 'Shenzhen Mindray Bio-Medical', koreanName: '마인드레이 (마이루이의료)', industry: '환자감시장치/의료기기', targetPe: 28 },
  { country: 'CN', ticker: '603259', name: 'WuXi AppTec', koreanName: '우시앱텍 (약명강덕)', industry: '글로벌바이오CDMO', targetPe: 20 },
  { country: 'CN', ticker: '600048', name: 'Poly Developments and Holdings', koreanName: '보리부동산 (폴리)', industry: '국유부동산개발', targetPe: 10 },
  { country: 'CN', ticker: '601668', name: 'China State Construction Engineering', koreanName: '중국건축 (CSCEC)', industry: '글로벌토목/인프라건설', targetPe: 5 },
  // Additional CN Leaders
  { country: 'CN', ticker: '002304', name: 'Jiangsu Yanghe Brewery', koreanName: '양하양조 (양허양조)', industry: '백주/프리미엄주류', targetPe: 16 },
  { country: 'CN', ticker: '600809', name: 'Shanxi Xinghuacun Fen Wine', koreanName: '산서행화촌분주 (펀주)', industry: '백주/주류', targetPe: 22 },
  { country: 'CN', ticker: '600585', name: 'Anhui Conch Cement', koreanName: '안휘해라시멘트 (콘치시멘트)', industry: '시멘트/건축자재', targetPe: 10 },
  { country: 'CN', ticker: '601628', name: 'China Life Insurance', koreanName: '중국생명보험', industry: '생명보험/금융', targetPe: 12 },
  { country: 'CN', ticker: '601601', name: 'China Pacific Insurance', koreanName: '중국태평양보험', industry: '손해보험/생명보험', targetPe: 10 },
  { country: 'CN', ticker: '600016', name: 'China Minsheng Banking Corp', koreanName: '민생은행', industry: '민간상업은행', targetPe: 5 },
  { country: 'CN', ticker: '601998', name: 'China CITIC Bank', koreanName: '중신은행', industry: '상업은행/금융', targetPe: 5 },
  { country: 'CN', ticker: '002142', name: 'Bank of Ningbo', koreanName: '영파은행 (닝보은행)', industry: '우량도시상업은행', targetPe: 8 },
  { country: 'CN', ticker: '600690', name: 'Haier Smart Home', koreanName: '하이얼 스마트홈', industry: '스마트가전/백색가전', targetPe: 14 },
  { country: 'CN', ticker: '000568', name: 'Luzhou Laojiao', koreanName: '노주고교 (루저우라오자오)', industry: '백주/명주', targetPe: 18 },
  { country: 'CN', ticker: '603288', name: 'Foshan Haitian Flavouring and Food', koreanName: '해천미업 (하이톈간장)', industry: '조미료/음식료', targetPe: 28 },
  { country: 'CN', ticker: '300015', name: 'Aier Eye Hospital Group', koreanName: '애이안과병원 (아이얼안과)', industry: '안과전문병원체인', targetPe: 30 },
  { country: 'CN', ticker: '000661', name: 'Changchun High-and-New Tech', koreanName: '장춘고신', industry: '성장호르몬/바이오', targetPe: 16 },
  { country: 'CN', ticker: '600763', name: 'Topchoice Medical Corporation', koreanName: '통책의료', industry: '치과체인병원/의료', targetPe: 30 },
  { country: 'CN', ticker: '600436', name: 'Zhangzhou Pientzehuang Pharmaceutical', koreanName: '편자황 (피엔즈황)', industry: '중국전통명약/제약', targetPe: 35 },
  { country: 'CN', ticker: '000538', name: 'Yunnan Baiyao Group', koreanName: '운남백약', industry: '한방의약품/헬스케어', targetPe: 20 },
  { country: 'CN', ticker: '601800', name: 'China Communications Construction', koreanName: '중국교통건설', industry: '해양항만/교량인프라', targetPe: 6 },
  { country: 'CN', ticker: '601186', name: 'China Railway Construction Corp', koreanName: '중국철도건설', industry: '고속철도/인프라', targetPe: 5 },
  { country: 'CN', ticker: '601390', name: 'China Railway Group', koreanName: '중국중철', industry: '철도인프라건설', targetPe: 5 },
  { country: 'CN', ticker: '601766', name: 'CRRC Corporation Limited', koreanName: '중국중차 (CRRC)', industry: '고속철도차량제조', targetPe: 12 },
  { country: 'CN', ticker: '600150', name: 'China CSSC Holdings', koreanName: '중국선박 (CSSC)', industry: '조선/해양방위', targetPe: 25 },
  { country: 'CN', ticker: '600875', name: 'Dongfang Electric Corp', koreanName: '동방전기', industry: '원자력/수력발전설비', targetPe: 16 },
  { country: 'CN', ticker: '600406', name: 'NARI Technology', koreanName: '국전남서 (NARI)', industry: '스마트그리드/전력망', targetPe: 22 },
  { country: 'CN', ticker: '002027', name: 'Focus Media Information Tech', koreanName: '분중미디어 (포커스미디어)', industry: '엘리베이터옥외광고', targetPe: 18 },
  { country: 'CN', ticker: '601006', name: 'Daqin Railway', koreanName: '대진철도 (다친철도)', industry: '석탄화물철도/고배당', targetPe: 10 },
  { country: 'CN', ticker: '600009', name: 'Shanghai International Airport', koreanName: '상하이국제공항 (푸둥공항)', industry: '공항인프라/면세임대', targetPe: 22 },
  { country: 'CN', ticker: '600018', name: 'Shanghai International Port (SIPG)', koreanName: '상하이국제항무', industry: '글로벌최대컨테이너항만', targetPe: 11 },
  { country: 'CN', ticker: '601919', name: 'COSCO SHIPPING Holdings', koreanName: '코스코해운 (중원해운)', industry: '글로벌컨테이너선사', targetPe: 8 },
  { country: 'CN', ticker: '002352', name: 'SF Holding', koreanName: '순풍홀딩스 (SF익스프레스)', industry: '프리미엄택배/물류', targetPe: 20 },
  { country: 'CN', ticker: '600233', name: 'YTO Express Group', koreanName: '원통택배 (위안퉁)', industry: '이커머스택배물류', targetPe: 14 }
];

// Combine all into unified catalog
const fullCatalog = [...krStocks, ...usStocks, ...vnStocks, ...cnStocks];

fs.writeFileSync(catalogPath, JSON.stringify(fullCatalog, null, 2), 'utf8');

console.log('Successfully expanded catalog:');
console.log('KR:', krStocks.length);
console.log('US:', usStocks.length);
console.log('VN:', vnStocks.length);
console.log('CN:', cnStocks.length);
console.log('Total:', fullCatalog.length);
