import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const catalogPath = path.join(__dirname, '../src/data/stockCatalog.json');
const currentCatalog = JSON.parse(fs.readFileSync(catalogPath, 'utf8'));

// Retain existing KR, VN, CN stocks
const nonUsStocks = currentCatalog.filter(s => s.country !== 'US');

// Comprehensive US S&P 500 + Nasdaq 100 + Popular Mega & Mid Caps (500+ items)
const usCatalog = [
  // 1. Megacap Tech & Semiconductor Leaders (70)
  { country: 'US', ticker: 'AAPL', name: 'Apple Inc.', koreanName: '애플', industry: '소프트웨어', targetPe: 28 },
  { country: 'US', ticker: 'MSFT', name: 'Microsoft Corporation', koreanName: '마이크로소프트', industry: '소프트웨어', targetPe: 32 },
  { country: 'US', ticker: 'NVDA', name: 'NVIDIA Corporation', koreanName: '엔비디아', industry: '반도체', targetPe: 40 },
  { country: 'US', ticker: 'GOOGL', name: 'Alphabet Inc. (Class A)', koreanName: '알파벳 A (구글)', industry: '인터넷/미디어', targetPe: 24 },
  { country: 'US', ticker: 'GOOG', name: 'Alphabet Inc. (Class C)', koreanName: '알파벳 C (구글)', industry: '인터넷/미디어', targetPe: 24 },
  { country: 'US', ticker: 'AMZN', name: 'Amazon.com Inc.', koreanName: '아마존', industry: '이커머스/클라우드', targetPe: 35 },
  { country: 'US', ticker: 'META', name: 'Meta Platforms Inc.', koreanName: '메타 (페이스북)', industry: '인터넷/소셜미디어', targetPe: 25 },
  { country: 'US', ticker: 'TSLA', name: 'Tesla Inc.', koreanName: '테슬라', industry: '전기차/에너지', targetPe: 45 },
  { country: 'US', ticker: 'AVGO', name: 'Broadcom Inc.', koreanName: '브로드컴', industry: '반도체', targetPe: 28 },
  { country: 'US', ticker: 'TSM', name: 'Taiwan Semiconductor (ADR)', koreanName: 'TSMC (대만반도체)', industry: '반도체파운드리', targetPe: 25 },
  { country: 'US', ticker: 'ASML', name: 'ASML Holding (ADR)', koreanName: 'ASML (네덜란드노광장비)', industry: '반도체장비', targetPe: 35 },
  { country: 'US', ticker: 'AMD', name: 'Advanced Micro Devices', koreanName: 'AMD (어드밴스드 마이크로 디바이시스)', industry: '반도체', targetPe: 35 },
  { country: 'US', ticker: 'QCOM', name: 'Qualcomm Inc.', koreanName: '퀄컴', industry: '반도체', targetPe: 18 },
  { country: 'US', ticker: 'TXN', name: 'Texas Instruments', koreanName: '텍사스 인스트루먼트', industry: '아날로그반도체', targetPe: 25 },
  { country: 'US', ticker: 'INTC', name: 'Intel Corporation', koreanName: '인텔', industry: '반도체', targetPe: 15 },
  { country: 'US', ticker: 'AMAT', name: 'Applied Materials', koreanName: '어플라이드 머티어리얼즈', industry: '반도체장비', targetPe: 22 },
  { country: 'US', ticker: 'LRCX', name: 'Lam Research Corp.', koreanName: '램리서치', industry: '반도체장비', targetPe: 24 },
  { country: 'US', ticker: 'MU', name: 'Micron Technology', koreanName: '마이크론 테크놀로지', industry: '메모리반도체', targetPe: 15 },
  { country: 'US', ticker: 'KLAC', name: 'KLA Corporation', koreanName: 'KLA (케이엘에이)', industry: '반도체검사장비', targetPe: 25 },
  { country: 'US', ticker: 'ADI', name: 'Analog Devices', koreanName: '아나로그 디바이스', industry: '아날로그반도체', targetPe: 25 },
  { country: 'US', ticker: 'MRVL', name: 'Marvell Technology', koreanName: '마벨 테크놀로지', industry: 'AI네트워크반도체', targetPe: 35 },
  { country: 'US', ticker: 'NXPI', name: 'NXP Semiconductors', koreanName: 'NXP 반도체 (차량용반도체)', industry: '차량용반도체', targetPe: 18 },
  { country: 'US', ticker: 'MCHP', name: 'Microchip Technology', koreanName: '마이크로칩 테크놀로지', industry: 'MCU반도체', targetPe: 20 },
  { country: 'US', ticker: 'ON', name: 'ON Semiconductor', koreanName: '온세미 (온세미컨덕터)', industry: '전력반도체/SiC', targetPe: 18 },
  { country: 'US', ticker: 'MPWR', name: 'Monolithic Power Systems', koreanName: '모놀리식 파워 시스템즈 (MPS)', industry: '전력관리반도체', targetPe: 35 },
  { country: 'US', ticker: 'ARM', name: 'Arm Holdings plc (ADR)', koreanName: 'ARM 홀딩스', industry: '반도체설계/아키텍처', targetPe: 45 },
  { country: 'US', ticker: 'PLTR', name: 'Palantir Technologies', koreanName: '팔란티어 테크놀로지스', industry: 'AI빅데이터/국방SW', targetPe: 50 },
  { country: 'US', ticker: 'ORCL', name: 'Oracle Corporation', koreanName: '오라클', industry: '데이터베이스/클라우드', targetPe: 25 },
  { country: 'US', ticker: 'CRM', name: 'Salesforce Inc.', koreanName: '세일즈포스', industry: '클라우드CRM', targetPe: 28 },
  { country: 'US', ticker: 'ADBE', name: 'Adobe Inc.', koreanName: '어도비', industry: '소프트웨어', targetPe: 30 },
  { country: 'US', ticker: 'NOW', name: 'ServiceNow Inc.', koreanName: '서비스나우', industry: '클라우드소프트웨어', targetPe: 45 },
  { country: 'US', ticker: 'PANW', name: 'Palo Alto Networks', koreanName: '팔로알토 네트웍스', industry: '사이버보안', targetPe: 40 },
  { country: 'US', ticker: 'CRWD', name: 'CrowdStrike Holdings', koreanName: '크라우드스트라이크', industry: '엔드포인트보안', targetPe: 50 },
  { country: 'US', ticker: 'FTNT', name: 'Fortinet Inc.', koreanName: '포티넷', industry: '네트워크방화벽', targetPe: 35 },
  { country: 'US', ticker: 'SNPS', name: 'Synopsys Inc.', koreanName: '시놉시스', industry: '반도체EDA', targetPe: 35 },
  { country: 'US', ticker: 'CDNS', name: 'Cadence Design Systems', koreanName: '케이던스 디자인', industry: '반도체EDA', targetPe: 35 },
  { country: 'US', ticker: 'INTU', name: 'Intuit Inc.', koreanName: '인튜이트 (터보택스)', industry: '핀테크소프트웨어', targetPe: 30 },
  { country: 'US', ticker: 'IBM', name: 'International Business Machines', koreanName: 'IBM', industry: '하이브리드클라우드/AI', targetPe: 18 },
  { country: 'US', ticker: 'CSCO', name: 'Cisco Systems', koreanName: '시스코 시스템즈', industry: '네트워크장비', targetPe: 16 },
  { country: 'US', ticker: 'ACN', name: 'Accenture plc', koreanName: '액센츄어', industry: 'IT컨설팅/DX', targetPe: 25 },
  { country: 'US', ticker: 'APP', name: 'AppLovin Corporation', koreanName: '앱러빈', industry: 'AI모바일광고', targetPe: 30 },
  { country: 'US', ticker: 'SMCI', name: 'Super Micro Computer Inc.', koreanName: '슈퍼마이크로컴퓨터', industry: 'AI서버/수랭식서버', targetPe: 25 },
  { country: 'US', ticker: 'DELL', name: 'Dell Technologies Inc.', koreanName: '델 테크놀로지스', industry: 'AI서버/PC', targetPe: 16 },
  { country: 'US', ticker: 'HPE', name: 'Hewlett Packard Enterprise', koreanName: '휴렛팩커드 엔터프라이즈 (HPE)', industry: '엔터프라이즈서버', targetPe: 12 },
  { country: 'US', ticker: 'HPQ', name: 'HP Inc.', koreanName: 'HP', industry: 'PC/프린팅', targetPe: 11 },
  { country: 'US', ticker: 'ANET', name: 'Arista Networks', koreanName: '아리스타 네트웍스', industry: 'AI데이터센터스위치', targetPe: 35 },
  { country: 'US', ticker: 'SNOW', name: 'Snowflake Inc.', koreanName: '스노우플레이크', industry: '클라우드데이터웨어하우스', targetPe: 40 },
  { country: 'US', ticker: 'DDOG', name: 'Datadog Inc.', koreanName: '데이터독', industry: '클라우드모니터링/APM', targetPe: 40 },
  { country: 'US', ticker: 'NET', name: 'Cloudflare Inc.', koreanName: '클라우드플레어', industry: 'CDN/엣지컴퓨팅', targetPe: 45 },
  { country: 'US', ticker: 'ZS', name: 'Zscaler Inc.', koreanName: '지스케일러', industry: '클라우드보안/ZTNA', targetPe: 45 },
  { country: 'US', ticker: 'TEAM', name: 'Atlassian Corporation', koreanName: '아틀라시안 (지라/컨플루언스)', industry: '협업소프트웨어', targetPe: 35 },
  { country: 'US', ticker: 'WDAY', name: 'Workday Inc.', koreanName: '워크데이', industry: '클라우드HR/재무', targetPe: 30 },
  { country: 'US', ticker: 'MDB', name: 'MongoDB Inc.', koreanName: '몽고DB', industry: 'NoSQL데이터베이스', targetPe: 40 },
  { country: 'US', ticker: 'ESTC', name: 'Elastic N.V.', koreanName: '엘라스틱 (일래스틱서치)', industry: 'AI검색엔진/로그분석', targetPe: 30 },
  { country: 'US', ticker: 'VRSN', name: 'VeriSign Inc.', koreanName: '베리사인 (.com도메인)', industry: '도메인인프라', targetPe: 24 },
  { country: 'US', ticker: 'AKAM', name: 'Akamai Technologies', koreanName: '아카마이 테크놀로지스', industry: 'CDN/클라우드보안', targetPe: 16 },
  { country: 'US', ticker: 'FSLY', name: 'Fastly Inc.', koreanName: '패스틀리', industry: '엣지클라우드/CDN', targetPe: 25 },
  { country: 'US', ticker: 'PATH', name: 'UiPath Inc.', koreanName: '유아이패스', industry: 'RPA업무자동화', targetPe: 25 },
  { country: 'US', ticker: 'NTNX', name: 'Nutanix Inc.', koreanName: '뉴타닉스', industry: 'HCI/하이브리드클라우드', targetPe: 30 },
  { country: 'US', ticker: 'PSTG', name: 'Pure Storage Inc.', koreanName: '퓨어스토리지', industry: '올플래시스토리지', targetPe: 25 },
  { country: 'US', ticker: 'WDC', name: 'Western Digital Corp.', koreanName: '웨스턴디지털 (WD)', industry: 'HDD/NAND플래시', targetPe: 15 },
  { country: 'US', ticker: 'STX', name: 'Seagate Technology', koreanName: '씨게이트 테크놀로지', industry: 'HDD대용량스토리지', targetPe: 16 },
  { country: 'US', ticker: 'TER', name: 'Teradyne Inc.', koreanName: '테러다인 (로봇/반도체테스트)', industry: '반도체테스트장비/협동로봇', targetPe: 28 },
  { country: 'US', ticker: 'ENTG', name: 'Entegris Inc.', koreanName: '인테그리스', industry: '반도체특수가스/케미컬', targetPe: 28 },
  { country: 'US', ticker: 'MKSI', name: 'MKS Instruments', koreanName: 'MKS 인스트루먼츠', industry: '반도체공정제어/레이저', targetPe: 20 },
  { country: 'US', ticker: 'ONTO', name: 'Onto Innovation', koreanName: '온토 이노베이션', industry: '반도체계측/검사', targetPe: 26 },
  { country: 'US', ticker: 'CAMT', name: 'Camtek Ltd.', koreanName: '캠텍', industry: 'HBM패키징검사장비', targetPe: 30 },
  { country: 'US', ticker: 'COHR', name: 'Coherent Corp.', koreanName: '코히런트 (레이저/광통신)', industry: '광트랜시버/광통신소재', targetPe: 25 },
  { country: 'US', ticker: 'LITE', name: 'Lumentum Holdings', koreanName: '루멘텀 홀딩스', industry: '광모듈/3D센싱', targetPe: 22 },

  // 2. Healthcare, Pharma, Biotech & Medical Devices (60)
  { country: 'US', ticker: 'LLY', name: 'Eli Lilly and Company', koreanName: '일라이 릴리 (비만치료제 젭바운드/마운자로)', industry: '바이오/비만치료제', targetPe: 40 },
  { country: 'US', ticker: 'UNH', name: 'UnitedHealth Group', koreanName: '유나이티드헬스그룹', industry: '의료보험/헬스케어', targetPe: 20 },
  { country: 'US', ticker: 'JNJ', name: 'Johnson & Johnson', koreanName: '존슨앤존슨 (J&J)', industry: '의약품/의료기기', targetPe: 17 },
  { country: 'US', ticker: 'ABBV', name: 'AbbVie Inc.', koreanName: '애브비 (휴미라/스카이리치)', industry: '면역질환바이오', targetPe: 16 },
  { country: 'US', ticker: 'MRK', name: 'Merck & Co. Inc.', koreanName: '머크 (면역항암제 키트루다)', industry: '항암신약/바이오', targetPe: 16 },
  { country: 'US', ticker: 'TMO', name: 'Thermo Fisher Scientific', koreanName: '써모피셔 사이언티픽', industry: '의료연구장비/바이오분석', targetPe: 26 },
  { country: 'US', ticker: 'ABT', name: 'Abbott Laboratories', koreanName: '애보트 (연속혈당측정기 프리스타일)', industry: '체외진단/심혈관의료기기', targetPe: 24 },
  { country: 'US', ticker: 'DHR', name: 'Danaher Corporation', koreanName: '다나허 (생명과학기기)', industry: '바이오프로세싱/진단', targetPe: 28 },
  { country: 'US', ticker: 'PFE', name: 'Pfizer Inc.', koreanName: '화이자', industry: '백신/글로벌제약', targetPe: 14 },
  { country: 'US', ticker: 'ISRG', name: 'Intuitive Surgical', koreanName: '인튜이티브 서지컬 (다빈치 수술로봇)', industry: '수술로봇/정밀의료', targetPe: 45 },
  { country: 'US', ticker: 'AMGN', name: 'Amgen Inc.', koreanName: '암젠', industry: '바이오시밀러/신약', targetPe: 16 },
  { country: 'US', ticker: 'BMY', name: 'Bristol-Myers Squibb', koreanName: '브리스톨 마이어스 스퀴브 (BMS)', industry: '항암제/면역치료', targetPe: 14 },
  { country: 'US', ticker: 'GILD', name: 'Gilead Sciences', koreanName: '길리어드 사이언스 (HIV/간염치료제)', industry: '항바이러스치료제', targetPe: 15 },
  { country: 'US', ticker: 'VRTX', name: 'Vertex Pharmaceuticals', koreanName: '버텍스 파마슈티컬스 (낭포성섬유증/CRISPR)', industry: '희귀난치질환바이오', targetPe: 28 },
  { country: 'US', ticker: 'REGN', name: 'Regeneron Pharmaceuticals', koreanName: '리제네론 파마슈티컬스 (아일리아/듀피젠트)', industry: '항체신약개발', targetPe: 22 },
  { country: 'US', ticker: 'MDT', name: 'Medtronic plc', koreanName: '메드트로닉 (심장박동기/스텐트)', industry: '글로벌의료기기', targetPe: 18 },
  { country: 'US', ticker: 'BSX', name: 'Boston Scientific Corp.', koreanName: '보스턴 사이언티픽', industry: '중재시술의료기기', targetPe: 30 },
  { country: 'US', ticker: 'SYK', name: 'Stryker Corporation', koreanName: '스트라이커 (인공관절/정형외과)', industry: '정형외과의료기기/마코로봇', targetPe: 28 },
  { country: 'US', ticker: 'EW', name: 'Edwards Lifesciences', koreanName: '에드워즈 라이프사이언시스 (인공심장판막)', industry: '심장판막/TAVR', targetPe: 28 },
  { country: 'US', ticker: 'ZTS', name: 'Zoetis Inc.', koreanName: '조에티스 (글로벌 1위 동물의약품)', industry: '반려동물/축산의약품', targetPe: 28 },
  { country: 'US', ticker: 'IDXX', name: 'IDEXX Laboratories', koreanName: '아이덱스 라보라토리스 (동물체외진단)', industry: '반려동물진단장비', targetPe: 40 },
  { country: 'US', ticker: 'DXCM', name: 'DexCom Inc.', koreanName: '덱스콤 (연속혈당측정기 CGM)', industry: '당뇨관리의료기기', targetPe: 35 },
  { country: 'US', ticker: 'PODD', name: 'Insulet Corporation', koreanName: '인슐렛 (옴니팟 웨어러블인슐린펌프)', industry: '웨어러블인슐린펌프', targetPe: 40 },
  { country: 'US', ticker: 'ALGN', name: 'Align Technology', koreanName: '얼라인 테크놀로지 (인비절라인 투명교정)', industry: '디지털치과교정', targetPe: 25 },
  { country: 'US', ticker: 'RMD', name: 'ResMed Inc.', koreanName: '레즈메드 (수면무호흡증 양압기)', industry: '수면호흡의료기기', targetPe: 26 },
  { country: 'US', ticker: 'ELV', name: 'Elevance Health', koreanName: '엘레반스 헬스 (앤섬)', industry: '건강보험/의료서비스', targetPe: 14 },
  { country: 'US', ticker: 'CVS', name: 'CVS Health Corporation', koreanName: 'CVS 헬스 (약국체인/애트나보험)', industry: '약국체인/PBM', targetPe: 10 },
  { country: 'US', ticker: 'CI', name: 'The Cigna Group', koreanName: '시그나 그룹', industry: '글로벌의료보험/PBM', targetPe: 13 },
  { country: 'US', ticker: 'HUM', name: 'Humana Inc.', koreanName: '휴매나', industry: '메디케어건강보험', targetPe: 14 },
  { country: 'US', ticker: 'MCK', name: 'McKesson Corporation', koreanName: '맥케슨', industry: '의약품유통도매', targetPe: 16 },
  { country: 'US', ticker: 'COR', name: 'Cencora Inc.', koreanName: '센코라 (구 아메리소스버겐)', industry: '의약품유통', targetPe: 16 },
  { country: 'US', ticker: 'CAH', name: 'Cardinal Health', koreanName: '카디널 헬스', industry: '의약품/의료용품유통', targetPe: 15 },
  { country: 'US', ticker: 'BIIB', name: 'Biogen Inc.', koreanName: '바이오젠 (알츠하이머/레켐비)', industry: '신경퇴행성질환신약', targetPe: 15 },
  { country: 'US', ticker: 'ILMN', name: 'Illumina Inc.', koreanName: '일루미나 (유전자염기서열분석)', industry: '유전체시퀀싱/NGS', targetPe: 25 },
  { country: 'US', ticker: 'MRNA', name: 'Moderna Inc.', koreanName: '모더나 (mRNA백신)', industry: 'mRNA신약/항암백신', targetPe: 25 },
  { country: 'US', ticker: 'BNTX', name: 'BioNTech SE (ADR)', koreanName: '바이오엔텍', industry: 'mRNA면역항암치료', targetPe: 20 },
  { country: 'US', ticker: 'CRSP', name: 'CRISPR Therapeutics', koreanName: '크리스퍼 테라퓨틱스 (유전자편집가위)', industry: '유전자편집치료', targetPe: 35 },
  { country: 'US', ticker: 'NTLA', name: 'Intellia Therapeutics', koreanName: '인텔리아 테라퓨틱스', industry: '체내CRISPR유전자교정', targetPe: 30 },
  { country: 'US', ticker: 'BEAM', name: 'Beam Therapeutics', koreanName: '빔 테라퓨틱스 (염기교정)', industry: '염기편집유전자치료', targetPe: 30 },
  { country: 'US', ticker: 'DNA', name: 'Ginkgo Bioworks', koreanName: '징코 바이오웍스', industry: '합성생물학파운드리', targetPe: 25 },
  { country: 'US', ticker: 'ALNY', name: 'Alnylam Pharmaceuticals', koreanName: '앨나일람 파마슈티컬스 (RNAi치료제)', industry: 'RNA간섭치료제', targetPe: 35 },
  { country: 'US', ticker: 'INCY', name: 'Incyte Corporation', koreanName: '인사이트 (자카비)', industry: '혈액암/희귀질환', targetPe: 18 },
  { country: 'US', ticker: 'NVO', name: 'Novo Nordisk (ADR)', koreanName: '노보 노디스크 (위고비/오젬픽)', industry: 'GLP-1비만/당뇨치료제', targetPe: 35 },
  { country: 'US', ticker: 'AZN', name: 'AstraZeneca (ADR)', koreanName: '아스트라제네카', industry: '항암제/희귀질환', targetPe: 18 },
  { country: 'US', ticker: 'NVS', name: 'Novartis AG (ADR)', koreanName: '노바티스', industry: '방사성의약품/유전자치료', targetPe: 16 },
  { country: 'US', ticker: 'SNY', name: 'Sanofi (ADR)', koreanName: '사노피 (듀피젠트)', industry: '면역질환/백신', targetPe: 13 },
  { country: 'US', ticker: 'GSK', name: 'GSK plc (ADR)', koreanName: 'GSK (글락소스미스클라인/싱그릭스)', industry: '백신/호흡기치료제', targetPe: 12 },

  // 3. Financials, Banks, Insurance & FinTech (55)
  { country: 'US', ticker: 'BRK.B', name: 'Berkshire Hathaway (Class B)', koreanName: '버크셔 해서웨이 B (워렌 버핏)', industry: '지주사/보험/투자', targetPe: 18 },
  { country: 'US', ticker: 'JPM', name: 'JPMorgan Chase & Co.', koreanName: 'JP모건 체이스', industry: '글로벌 1위 투자은행', targetPe: 13 },
  { country: 'US', ticker: 'V', name: 'Visa Inc.', koreanName: '비자 (Visa)', industry: '글로벌결제네트워크', targetPe: 28 },
  { country: 'US', ticker: 'MA', name: 'Mastercard Incorporated', koreanName: '마스터카드', industry: '글로벌결제네트워크', targetPe: 30 },
  { country: 'US', ticker: 'BAC', name: 'Bank of America Corp.', koreanName: '뱅크오브아메리카 (BofA)', industry: '상업은행/금융', targetPe: 12 },
  { country: 'US', ticker: 'WFC', name: 'Wells Fargo & Company', koreanName: '웰스파고', industry: '상업은행/주택담보대출', targetPe: 12 },
  { country: 'US', ticker: 'MS', name: 'Morgan Stanley', koreanName: '모건스탠리', industry: '투자은행/자산관리(WM)', targetPe: 15 },
  { country: 'US', ticker: 'GS', name: 'The Goldman Sachs Group', koreanName: '골드만삭스', industry: '글로벌투자은행/M&A', targetPe: 14 },
  { country: 'US', ticker: 'BLK', name: 'BlackRock Inc.', koreanName: '블랙록 (iShares ETF)', industry: '글로벌 1위 자산운용사', targetPe: 22 },
  { country: 'US', ticker: 'SCHW', name: 'Charles Schwab Corp.', koreanName: '찰스 슈왑', industry: '리테일증권/자산관리', targetPe: 20 },
  { country: 'US', ticker: 'AXP', name: 'American Express Company', koreanName: '아메리칸 익스프레스 (아멕스)', industry: '프리미엄신용카드/결제', targetPe: 18 },
  { country: 'US', ticker: 'C', name: 'Citigroup Inc.', koreanName: '씨티그룹 (씨티은행)', industry: '글로벌기업금융/외환', targetPe: 10 },
  { country: 'US', ticker: 'SPGI', name: 'S&P Global Inc.', koreanName: 'S&P 글로벌 (신용평가/지수)', industry: '신용평가/금융인텔리전스', targetPe: 30 },
  { country: 'US', ticker: 'MCO', name: 'Moody\'s Corporation', koreanName: '무디스 (글로벌신용평가)', industry: '신용평가/리스크관리', targetPe: 32 },
  { country: 'US', ticker: 'CME', name: 'CME Group Inc.', koreanName: 'CME 그룹 (시카고파생상품거래소)', industry: '선물옵션파생상품거래소', targetPe: 24 },
  { country: 'US', ticker: 'ICE', name: 'Intercontinental Exchange', koreanName: 'ICE (뉴욕증권거래소 NYSE 모회사)', industry: '증권거래소/모기지기술', targetPe: 22 },
  { country: 'US', ticker: 'NDAQ', name: 'Nasdaq Inc.', koreanName: '나스닥 (Nasdaq 거래소)', industry: '금융인프라/거래소', targetPe: 24 },
  { country: 'US', ticker: 'COIN', name: 'Coinbase Global Inc.', koreanName: '코인베이스 (미국최대가상자산거래소)', industry: '가상자산/크립토거래소', targetPe: 30 },
  { country: 'US', ticker: 'HOOD', name: 'Robinhood Markets', koreanName: '로빈후드 (수수료무료주식/코인)', industry: '핀테크증권앱', targetPe: 25 },
  { country: 'US', ticker: 'MSTR', name: 'MicroStrategy Inc.', koreanName: '마이크로스트래티지 (비트코인보유기업)', industry: '비트코인준비금/BI', targetPe: 40 },
  { country: 'US', ticker: 'MARA', name: 'MARA Holdings Inc.', koreanName: '마라톤 디지털 (비트코인채굴)', industry: '비트코인채굴인프라', targetPe: 25 },
  { country: 'US', ticker: 'RIOT', name: 'Riot Platforms', koreanName: '라이엇 플랫폼', industry: '비트코인채굴', targetPe: 25 },
  { country: 'US', ticker: 'CLSK', name: 'CleanSpark Inc.', koreanName: '클린스파크', industry: '친환경비트코인채굴', targetPe: 25 },
  { country: 'US', ticker: 'PYPL', name: 'PayPal Holdings', koreanName: '페이팔 (PayPal/Venmo)', industry: '글로벌전자결제/핀테크', targetPe: 16 },
  { country: 'US', ticker: 'SQ', name: 'Block Inc. (Square)', koreanName: '블록 (스퀘어/캐시앱)', industry: '디지털결제/모바일뱅킹', targetPe: 25 },
  { country: 'US', ticker: 'SOFI', name: 'SoFi Technologies', koreanName: '소파이 테크놀로지스 (네오뱅크)', industry: '모바일종합디지털금융', targetPe: 25 },
  { country: 'US', ticker: 'AFRM', name: 'Affirm Holdings', koreanName: '어펌 홀딩스 (선구매후결제 BNPL)', industry: 'BNPL할부결제핀테크', targetPe: 30 },
  { country: 'US', ticker: 'UPST', name: 'Upstart Holdings', koreanName: '업스타트 (AI신용평가/대출)', industry: 'AI대출중개플랫폼', targetPe: 30 },
  { country: 'US', ticker: 'PGR', name: 'The Progressive Corporation', koreanName: '프로그레시브 (자동차보험)', industry: '다이렉트자동차보험', targetPe: 16 },
  { country: 'US', ticker: 'TRV', name: 'The Travelers Companies', koreanName: '트래블러스 (기업/손해보험)', industry: '상업용손해보험', targetPe: 12 },
  { country: 'US', ticker: 'ALL', name: 'The Allstate Corporation', koreanName: '올스테이트', industry: '개인손해보험', targetPe: 12 },
  { country: 'US', ticker: 'CB', name: 'Chubb Limited', koreanName: '처브 (Chubb 보험)', industry: '글로벌손해보험', targetPe: 12 },
  { country: 'US', ticker: 'AIG', name: 'American International Group', koreanName: 'AIG', industry: '글로벌종합보험', targetPe: 10 },
  { country: 'US', ticker: 'MET', name: 'MetLife Inc.', koreanName: '메트라이프 (생명보험)', industry: '생명보험/퇴직연금', targetPe: 10 },
  { country: 'US', ticker: 'PRU', name: 'Prudential Financial', koreanName: '푸르덴셜 파이낸셜', industry: '생명보험/자산운용', targetPe: 10 },
  { country: 'US', ticker: 'AFL', name: 'Aflac Incorporated', koreanName: '아플락 (암보험/특약보험)', industry: '보충건강보험/암보험', targetPe: 11 },
  { country: 'US', ticker: 'USB', name: 'U.S. Bancorp', koreanName: 'US 뱅코프', industry: '대형지역상업은행', targetPe: 11 },
  { country: 'US', ticker: 'PNC', name: 'The PNC Financial Services', koreanName: 'PNC 파이낸셜', industry: '지역상업은행', targetPe: 12 },
  { country: 'US', ticker: 'TFC', name: 'Truist Financial Corp', koreanName: '트루이스트 파이낸셜', industry: '동남부대형은행', targetPe: 11 },
  { country: 'US', ticker: 'BK', name: 'The Bank of New York Mellon', koreanName: 'BNY 멜론 (수탁은행)', industry: '글로벌자산수탁/관리', targetPe: 13 },
  { country: 'US', ticker: 'STT', name: 'State Street Corporation', koreanName: '스테이트 스트리트 (SPDR ETF)', industry: '수탁은행/ETF운용', targetPe: 12 },
  { country: 'US', ticker: 'COF', name: 'Capital One Financial', koreanName: '캐피탈원', industry: '신용카드/소비자금융', targetPe: 10 },
  { country: 'US', ticker: 'DFS', name: 'Discover Financial Services', koreanName: '디스커버 파이낸셜', industry: '신용카드결제네트워크', targetPe: 10 },
  { country: 'US', ticker: 'SYF', name: 'Synchrony Financial', koreanName: '싱크로니 파이낸셜', industry: '유통사제휴신용카드', targetPe: 8 },

  // 4. Consumer, Retail, Entertainment & Travel (60)
  { country: 'US', ticker: 'WMT', name: 'Walmart Inc.', koreanName: '월마트 (글로벌 1위 유통체인)', industry: '대형할인점/이커머스', targetPe: 26 },
  { country: 'US', ticker: 'COST', name: 'Costco Wholesale Corp.', koreanName: '코스트코 (창고형회원제할인점)', industry: '창고형회원제유통', targetPe: 40 },
  { country: 'US', ticker: 'PG', name: 'Procter & Gamble Co.', koreanName: '프록터 앤 갬블 (P&G / 질레트/다우니)', industry: '생활용품/소비재', targetPe: 24 },
  { country: 'US', ticker: 'HD', name: 'The Home Depot Inc.', koreanName: '홈디포 (주택개조인테리어유통)', industry: '주택개선자재유통', targetPe: 22 },
  { country: 'US', ticker: 'KO', name: 'The Coca-Cola Company', koreanName: '코카콜라 (워렌버핏배당주)', industry: '음료/탄산음료', targetPe: 23 },
  { country: 'US', ticker: 'PEP', name: 'PepsiCo Inc.', koreanName: '펩시코 (펩시/레이즈/도리토스)', industry: '음료/스낵식품', targetPe: 21 },
  { country: 'US', ticker: 'MCD', name: 'McDonald\'s Corporation', koreanName: '맥도날드', industry: '패스트푸드프랜차이즈', targetPe: 24 },
  { country: 'US', ticker: 'NKE', name: 'Nike Inc.', koreanName: '나이키 (스포츠웨어/에어조던)', industry: '스포츠의류/신발', targetPe: 25 },
  { country: 'US', ticker: 'SBUX', name: 'Starbucks Corporation', koreanName: '스타벅스', industry: '스페셜티커피/외식체인', targetPe: 24 },
  { country: 'US', ticker: 'TGT', name: 'Target Corporation', koreanName: '타겟 (대형할인매장)', industry: '대형소매유통', targetPe: 15 },
  { country: 'US', ticker: 'LOW', name: 'Lowe\'s Companies', koreanName: '로우스 (주택건축자재)', industry: '주택개선소매', targetPe: 18 },
  { country: 'US', ticker: 'PM', name: 'Philip Morris International', koreanName: '필립모리스 (아이코스/말보로)', industry: '전자담배/담배', targetPe: 17 },
  { country: 'US', ticker: 'MO', name: 'Altria Group Inc.', koreanName: '알트리아 (고배당담배주)', industry: '담배/소비재', targetPe: 10 },
  { country: 'US', ticker: 'CL', name: 'Colgate-Palmolive', koreanName: '콜게이트 (치약/구강케어)', industry: '구강/퍼스널케어', targetPe: 25 },
  { country: 'US', ticker: 'MDLZ', name: 'Mondelez International', koreanName: '몬델리즈 (오레오/토블론)', industry: '비스킷/초콜릿제과', targetPe: 20 },
  { country: 'US', ticker: 'EL', name: 'The Estée Lauder Companies', koreanName: '에스티로더 (라메르/맥/조말론)', industry: '프리미엄화장품/뷰티', targetPe: 25 },
  { country: 'US', ticker: 'DIS', name: 'The Walt Disney Company', koreanName: '디즈니 (마블/스타워즈/디즈니+)', industry: '미디어/테마파크/OTT', targetPe: 22 },
  { country: 'US', ticker: 'NFLX', name: 'Netflix Inc.', koreanName: '넷플릭스 (글로벌 1위 OTT)', industry: 'OTT스트리밍', targetPe: 35 },
  { country: 'US', ticker: 'CMCSA', name: 'Comcast Corporation', koreanName: '컴캐스트 (유니버설픽처스/NBC)', industry: '케이블방송/엔터테인먼트', targetPe: 12 },
  { country: 'US', ticker: 'WBD', name: 'Warner Bros. Discovery', koreanName: '워너 브라더스 디스커버리 (HBO/맥스)', industry: '영화/미디어/스트리밍', targetPe: 12 },
  { country: 'US', ticker: 'PARA', name: 'Paramount Global', koreanName: '파라마운트 글로벌', industry: '방송/영화제작', targetPe: 10 },
  { country: 'US', ticker: 'SPOT', name: 'Spotify Technology S.A.', koreanName: '스포티파이 (글로벌 1위 음원)', industry: '음악스트리밍', targetPe: 40 },
  { country: 'US', ticker: 'UBER', name: 'Uber Technologies', koreanName: '우버 (차량호출/우버이츠)', industry: '모빌리티/음식배달', targetPe: 30 },
  { country: 'US', ticker: 'DASH', name: 'DoorDash Inc.', koreanName: '도어대시 (미국 1위 음식배달)', industry: '온라인음식배달', targetPe: 35 },
  { country: 'US', ticker: 'LYFT', name: 'Lyft Inc.', koreanName: '리프트 (차량공유)', industry: '라이드셰어링', targetPe: 25 },
  { country: 'US', ticker: 'ABNB', name: 'Airbnb Inc.', koreanName: '에어비앤비 (숙박공유)', industry: '글로벌숙박공유/여행', targetPe: 28 },
  { country: 'US', ticker: 'BKNG', name: 'Booking Holdings Inc.', koreanName: '부킹홀딩스 (아고다/부킹닷컴)', industry: '온라인여행예약(OTA)', targetPe: 24 },
  { country: 'US', ticker: 'EXPE', name: 'Expedia Group', koreanName: '익스피디아 (호텔스닷컴)', industry: '온라인여행플랫폼', targetPe: 16 },
  { country: 'US', ticker: 'MAR', name: 'Marriott International', koreanName: '메리어트 인터내셔널 (글로벌호텔체인)', industry: '글로벌호텔체인/리조트', targetPe: 24 },
  { country: 'US', ticker: 'HLT', name: 'Hilton Worldwide Holdings', koreanName: '힐튼 호텔 (힐튼 월드와이드)', industry: '호텔/호스피탈리티', targetPe: 26 },
  { country: 'US', ticker: 'H', name: 'Hyatt Hotels Corporation', koreanName: '하얏트 호텔', industry: '럭셔리호텔체인', targetPe: 25 },
  { country: 'US', ticker: 'CMG', name: 'Chipotle Mexican Grill', koreanName: '치폴레 (멕시칸 그릴)', industry: '패스트캐주얼외식', targetPe: 40 },
  { country: 'US', ticker: 'YUM', name: 'Yum! Brands Inc.', koreanName: '얌 브랜즈 (KFC/피자헛/타코벨)', industry: '패스트푸드프랜차이즈', targetPe: 22 },
  { country: 'US', ticker: 'DPZ', name: 'Domino\'s Pizza Inc.', koreanName: '도미노 피자', industry: '피자배달프랜차이즈', targetPe: 26 },
  { country: 'US', ticker: 'LULU', name: 'Lululemon Athletica', koreanName: '룰루레몬 (요가복/애슬레저)', industry: '프리미엄스포츠의류', targetPe: 24 },
  { country: 'US', ticker: 'DECK', name: 'Deckers Outdoor Corp', koreanName: '데커스 아웃도어 (호카 러닝화/어그부츠)', industry: '러닝화/신발브랜드', targetPe: 26 },
  { country: 'US', ticker: 'ONON', name: 'On Holding AG', koreanName: '온 홀딩 (온러닝/스위스러닝화)', industry: '프리미엄러닝화', targetPe: 35 },
  { country: 'US', ticker: 'CROX', name: 'Crocs Inc.', koreanName: '크록스 (샌들/클로그)', industry: '캐주얼신발', targetPe: 12 },
  { country: 'US', ticker: 'TJX', name: 'The TJX Companies', koreanName: 'TJX 컴퍼니 (TJ맥스/마샬스)', industry: '오프프라이스패션유통', targetPe: 24 },
  { country: 'US', ticker: 'ROST', name: 'Ross Stores Inc.', koreanName: '로스 스토어', industry: '할인패션아울렛', targetPe: 22 },
  { country: 'US', ticker: 'DLTR', name: 'Dollar Tree Inc.', koreanName: '달러트리 (1달러샵)', industry: '달러스토어/초저가유통', targetPe: 15 },
  { country: 'US', ticker: 'DG', name: 'Dollar General Corp', koreanName: '달러 제너럴', industry: '할인소매점', targetPe: 15 },
  { country: 'US', ticker: 'KMB', name: 'Kimberly-Clark Corp', koreanName: '킴벌리 클라크 (하기스/크리넥스)', industry: '위생용품/제지', targetPe: 18 },
  { country: 'US', ticker: 'GIS', name: 'General Mills Inc.', koreanName: '제너럴 밀스 (시리얼/하겐다즈)', industry: '가공식품/스낵', targetPe: 15 },
  { country: 'US', ticker: 'K', name: 'Kellanova', koreanName: '켈라노바 (구 켈로그/프링글스)', industry: '스낵/시리얼', targetPe: 18 },
  { country: 'US', ticker: 'HSY', name: 'The Hershey Company', koreanName: '허쉬 (초콜릿/키세스)', industry: '제과/초콜릿', targetPe: 20 },
  { country: 'US', ticker: 'KHC', name: 'The Kraft Heinz Company', koreanName: '크래프트 하인즈 (하인즈케첩/치즈)', industry: '식품/소스류', targetPe: 12 },
  { country: 'US', ticker: 'TSN', name: 'Tyson Foods Inc.', koreanName: '타이슨 푸드 (미국 1위 육가공)', industry: '육류가공/단백질식품', targetPe: 14 },
  { country: 'US', ticker: 'STZ', name: 'Constellation Brands', koreanName: '컨스텔레이션 브랜즈 (코로나맥주/와인)', industry: '맥주/주류수입', targetPe: 18 },
  { country: 'US', ticker: 'TAP', name: 'Molson Coors Beverage', koreanName: '몰슨 쿠어스 (쿠어스맥주)', industry: '맥주/음료', targetPe: 11 },
  { country: 'US', ticker: 'BTI', name: 'British American Tobacco (ADR)', koreanName: 'BAT (던힐/글로/고배당)', industry: '담배/소비재', targetPe: 8 },

  // 5. Industrials, Aerospace, Defense, Energy & EV (65)
  { country: 'US', ticker: 'XOM', name: 'Exxon Mobil Corporation', koreanName: '엑슨모빌 (미국 1위 정유에너지)', industry: '석유/종합에너지', targetPe: 13 },
  { country: 'US', ticker: 'CVX', name: 'Chevron Corporation', koreanName: '셰브론', industry: '석유/천연가스', targetPe: 13 },
  { country: 'US', ticker: 'COP', name: 'ConocoPhillips', koreanName: '코노코필립스', industry: '석유가스탐사/생산(E&P)', targetPe: 12 },
  { country: 'US', ticker: 'EOG', name: 'EOG Resources Inc.', koreanName: 'EOG 리소스 (셰일오일)', industry: '셰일가스/원유생산', targetPe: 11 },
  { country: 'US', ticker: 'SLB', name: 'Schlumberger Limited (SLB)', koreanName: '슐룸베르거 (유전서비스)', industry: '유전개발기술/에너지서비스', targetPe: 15 },
  { country: 'US', ticker: 'HAL', name: 'Halliburton Company', koreanName: '할리버튼 (시추서비스)', industry: '유전서비스/시추', targetPe: 12 },
  { country: 'US', ticker: 'BKR', name: 'Baker Hughes Company', koreanName: '베이커휴즈 (터보가스기계)', industry: '에너지장비/LNG터빈', targetPe: 16 },
  { country: 'US', ticker: 'OXY', name: 'Occidental Petroleum', koreanName: '옥시덴탈 페트롤리움 (워렌버핏셰일주)', industry: '셰일오일/탄소포집', targetPe: 12 },
  { country: 'US', ticker: 'VLO', name: 'Valero Energy Corp', koreanName: '발레로 에너지 (정제마진)', industry: '원유정제/신재생디젤', targetPe: 10 },
  { country: 'US', ticker: 'MPC', name: 'Marathon Petroleum Corp', koreanName: '마라톤 페트롤리움', industry: '석유정제/파이프라인', targetPe: 10 },
  { country: 'US', ticker: 'PSX', name: 'Phillips 66', koreanName: '필립스 66', industry: '석유정제/화학/미드스트림', targetPe: 11 },
  { country: 'US', ticker: 'KMI', name: 'Kinder Morgan Inc.', koreanName: '킨더모건 (천연가스파이프라인)', industry: '가스파이프라인인프라', targetPe: 16 },
  { country: 'US', ticker: 'WMB', name: 'The Williams Companies', koreanName: '윌리엄스 컴퍼니 (가스인프라)', industry: '천연가스수송인프라', targetPe: 16 },
  { country: 'US', ticker: 'CAT', name: 'Caterpillar Inc.', koreanName: '캐터필러 (건설/광산기계)', industry: '건설기계/중장비', targetPe: 17 },
  { country: 'US', ticker: 'DE', name: 'Deere & Company', koreanName: '디어 (존디어/스마트농기계)', industry: '정밀농업기계/트랙터', targetPe: 15 },
  { country: 'US', ticker: 'GE', name: 'GE Aerospace', koreanName: 'GE 에어로스페이스 (항공기제트엔진)', industry: '민항기제트엔진/방산', targetPe: 30 },
  { country: 'US', ticker: 'GEV', name: 'GE Vernova Inc.', koreanName: 'GE 베르노바 (가스터빈/전력망)', industry: '전력발전터빈/풍력', targetPe: 35 },
  { country: 'US', ticker: 'LMT', name: 'Lockheed Martin Corp.', koreanName: '록히드마틴 (F-35 스텔스전투기/사드)', industry: '방위산업/스텔스전투기', targetPe: 18 },
  { country: 'US', ticker: 'RTX', name: 'RTX Corporation', koreanName: '레이시온 (패트리어트미사일/프랫엔휘트니)', industry: '항공우주/유도미사일방산', targetPe: 20 },
  { country: 'US', ticker: 'BA', name: 'The Boeing Company', koreanName: '보잉 (민항기 737/787/방산)', industry: '민간항공기/우주방산', targetPe: 20 },
  { country: 'US', ticker: 'NOC', name: 'Northrop Grumman Corp', koreanName: '노스롭 그루먼 (B-21 스텔스폭격기)', industry: '스텔스폭격기/우주인공위성', targetPe: 18 },
  { country: 'US', ticker: 'GD', name: 'General Dynamics', koreanName: '제너럴 다이내믹스 (원자력잠수함/에이브람스)', industry: '잠수함/장갑차/걸프스트림', targetPe: 18 },
  { country: 'US', ticker: 'HON', name: 'Honeywell International', koreanName: '허니웰 인터내셔널 (항공자동화/센서)', industry: '항공전자/빌딩제어자동화', targetPe: 20 },
  { country: 'US', ticker: 'UNP', name: 'Union Pacific Corporation', koreanName: '유니온 퍼시픽 (미국최대철도운송)', industry: '철도화물물류', targetPe: 20 },
  { country: 'US', ticker: 'CSX', name: 'CSX Corporation', koreanName: 'CSX (동부화물철도)', industry: '철도화물운송', targetPe: 16 },
  { country: 'US', ticker: 'NSC', name: 'Norfolk Southern Corp', koreanName: '노퍽 서던', industry: '철도수송인프라', targetPe: 18 },
  { country: 'US', ticker: 'UPS', name: 'United Parcel Service', koreanName: 'UPS (글로벌특송택배)', industry: '글로벌항공화물/택배', targetPe: 16 },
  { country: 'US', ticker: 'FDX', name: 'FedEx Corporation', koreanName: '페덱스 (FedEx 특송)', industry: '항공특송화물/물류', targetPe: 14 },
  { country: 'US', ticker: 'WM', name: 'Waste Management Inc.', koreanName: '웨이스트 매니지먼트 (폐기물처리 1위)', industry: '폐기물수거/재활용', targetPe: 28 },
  { country: 'US', ticker: 'RSG', name: 'Republic Services Inc.', koreanName: '리퍼블릭 서비스 (폐기물관리)', industry: '환경위생/폐기물', targetPe: 26 },
  { country: 'US', ticker: 'ETN', name: 'Eaton Corporation plc', koreanName: '이튼 (AI데이터센터전력인프라)', industry: '전력관리/배전인프라', targetPe: 30 },
  { country: 'US', ticker: 'PH', name: 'Parker-Hannifin Corp', koreanName: '파커하니핀 (모션제어/유압)', industry: '정밀모션유압시스템', targetPe: 22 },
  { country: 'US', ticker: 'EMR', name: 'Emerson Electric Co.', koreanName: '에머슨 일렉트릭 (산업자동화)', industry: '공정자동화/계측제어', targetPe: 20 },
  { country: 'US', ticker: 'ROK', name: 'Rockwell Automation', koreanName: '로크웰 오토메이션 (스마트팩토리)', industry: '스마트공장/PLC제어', targetPe: 25 },
  { country: 'US', ticker: 'ITW', name: 'Illinois Tool Works', koreanName: '일리노이 툴 웍스', industry: '특수소재/산업용장비', targetPe: 22 },
  { country: 'US', ticker: 'TT', name: 'Trane Technologies plc', koreanName: '트레인 테크놀로지스 (공조/HVAC)', industry: '친환경냉난방HVAC', targetPe: 28 },
  { country: 'US', ticker: 'CARR', name: 'Carrier Global Corp', koreanName: '캐리어 글로벌 (에어컨/냉동공조)', industry: '스마트기후/냉난방공조', targetPe: 22 },
  { country: 'US', ticker: 'JCI', name: 'Johnson Controls International', koreanName: '존슨콘트롤즈 (스마트빌딩HVAC)', industry: '스마트빌딩/소방보안', targetPe: 18 },
  { country: 'US', ticker: 'RIVN', name: 'Rivian Automotive', koreanName: '리비안 (전기픽업트럭 R1T/R1S)', industry: '순수전기차(EV)', targetPe: 25 },
  { country: 'US', ticker: 'LCID', name: 'Lucid Group Inc.', koreanName: '루시드 (럭셔리전기차 에어)', industry: '프리미엄전기차', targetPe: 25 },
  { country: 'US', ticker: 'F', name: 'Ford Motor Company', koreanName: '포드 모터 (F-150 라이트닝)', industry: '완성차/픽업트럭', targetPe: 8 },
  { country: 'US', ticker: 'GM', name: 'General Motors Company', koreanName: '제너럴 모터스 (GM/얼티엄)', industry: '완성차/자율주행크루즈', targetPe: 7 },
  { country: 'US', ticker: 'RKLB', name: 'Rocket Lab USA', koreanName: '로켓랩 (소형로켓 일렉트론/뉴트론)', industry: '우주발사체/인공위성제조', targetPe: 35 },
  { country: 'US', ticker: 'ASTS', name: 'AST SpaceMobile', koreanName: 'AST 스페이스모바일 (스마트폰직접위성통신)', industry: '우주위성직접통신', targetPe: 40 },
  { country: 'US', ticker: 'LUNR', name: 'Intuitive Machines', koreanName: '인튜이티브 머신스 (달착륙선 오디세우스)', industry: 'NASA아르테미스달탐사', targetPe: 30 },
  { country: 'US', ticker: 'SPCE', name: 'Virgin Galactic', koreanName: '버진 갤럭틱 (우주관광)', industry: '민간상업우주관광', targetPe: 25 },
  { country: 'US', ticker: 'JOBY', name: 'Joby Aviation', koreanName: '조비 에비에이션 (도심항공교통 eVTOL)', industry: '도심항공교통(UAM)', targetPe: 35 },
  { country: 'US', ticker: 'ACHR', name: 'Archer Aviation', koreanName: '아처 에비에이션 (전기수직이착륙기 미드나잇)', industry: 'eVTOL에어택시', targetPe: 35 },
  { country: 'US', ticker: 'IONQ', name: 'IonQ Inc.', koreanName: '아이온큐 (이온트랩양자컴퓨팅)', industry: '양자컴퓨터하드웨어', targetPe: 50 },
  { country: 'US', ticker: 'RGTI', name: 'Rigetti Computing', koreanName: '리게티 컴퓨팅 (초전도양자)', industry: '초전도양자프로세서', targetPe: 40 },
  { country: 'US', ticker: 'QBTS', name: 'D-Wave Quantum', koreanName: '디웨이브 퀀텀 (양자어닐링)', industry: '상용양자어닐링컴퓨터', targetPe: 40 },

  // 6. Utilities, Clean Energy, Real Estate & Materials (55)
  { country: 'US', ticker: 'NEE', name: 'NextEra Energy', koreanName: '넥스트에라 에너지 (미국최대태양광/풍력)', industry: '신재생에너지/전력유틸리티', targetPe: 22 },
  { country: 'US', ticker: 'SO', name: 'The Southern Company', koreanName: '서던 컴퍼니 (원자력/전력)', industry: '원자력/전력유틸리티', targetPe: 18 },
  { country: 'US', ticker: 'DUK', name: 'Duke Energy Corporation', koreanName: '듀크 에너지', industry: '전력/천연가스공급', targetPe: 17 },
  { country: 'US', ticker: 'CEG', name: 'Constellation Energy Corp', koreanName: '콘스텔레이션 에너지 (원전전력공급/AI데이터센터)', industry: '원자력발전/클린에너지', targetPe: 28 },
  { country: 'US', ticker: 'VST', name: 'Vistra Corp', koreanName: '비스트라 (원자력/전력피크/AI데이터센터)', industry: '원자력/배터리ESS전력', targetPe: 25 },
  { country: 'US', ticker: 'NRG', name: 'NRG Energy Inc.', koreanName: 'NRG 에너지', industry: '소매전력/발전인프라', targetPe: 14 },
  { country: 'US', ticker: 'AEP', name: 'American Electric Power', koreanName: '아메리칸 일렉트릭 파워 (AEP)', industry: '초고압송전망/전력', targetPe: 16 },
  { country: 'US', ticker: 'SRE', name: 'Sempra', koreanName: '셈프라 (LNG터미널/가스전력)', industry: 'LNG수출터미널/유틸리티', targetPe: 16 },
  { country: 'US', ticker: 'EXC', name: 'Exelon Corporation', koreanName: '엑셀론 (송배전전력망)', industry: '규제송배전유틸리티', targetPe: 15 },
  { country: 'US', ticker: 'PCG', name: 'PG&E Corporation', koreanName: 'PG&E (캘리포니아전력가스)', industry: '전력가스유틸리티', targetPe: 13 },
  { country: 'US', ticker: 'XEL', name: 'Xcel Energy Inc.', koreanName: '엑셀 에너지 (풍력발전선도)', industry: '클린에너지전력', targetPe: 16 },
  { country: 'US', ticker: 'ED', name: 'Consolidated Edison', koreanName: '콘솔리데이티드 에디슨 (뉴욕전력/배당귀족)', industry: '전력/가스/스팀배당주', targetPe: 16 },
  { country: 'US', ticker: 'FSLR', name: 'First Solar Inc.', koreanName: '퍼스트솔라 (미국 1위 텔루르화카드뮴태양광)', industry: '박막태양광모듈', targetPe: 18 },
  { country: 'US', ticker: 'ENPH', name: 'Enphase Energy', koreanName: '엔페이즈 에너지 (마이크로인버터)', industry: '태양광마이크로인버터/ESS', targetPe: 25 },
  { country: 'US', ticker: 'SEDG', name: 'SolarEdge Technologies', koreanName: '솔라엣지 테크놀로지스', industry: '태양광인버터/옵티마이저', targetPe: 20 },
  { country: 'US', ticker: 'PLUG', name: 'Plug Power Inc.', koreanName: '플러그 파워 (그린수소/연료전지)', industry: '그린수소생산/연료전지', targetPe: 25 },
  { country: 'US', ticker: 'FCEL', name: 'FuelCell Energy', koreanName: '퓨얼셀 에너지', industry: '용융탄산염연료전지', targetPe: 20 },
  { country: 'US', ticker: 'BE', name: 'Bloom Energy Corp', koreanName: '블룸 에너지 (SOFC고체산화물연료전지)', industry: '데이터센터SOFC전원', targetPe: 30 },
  { country: 'US', ticker: 'LIN', name: 'Linde plc', koreanName: '린데 (글로벌 1위 산업용가스)', industry: '산업용특수가스/수소', targetPe: 30 },
  { country: 'US', ticker: 'APD', name: 'Air Products and Chemicals', koreanName: '에어 프로덕츠 (블루/그린수소프로젝트)', industry: '산업용가스/LNG장비', targetPe: 22 },
  { country: 'US', ticker: 'ECL', name: 'Ecolab Inc.', koreanName: '이콜랩 (수처리/위생솔루션)', industry: '산업용수처리/위생', targetPe: 30 },
  { country: 'US', ticker: 'SHW', name: 'The Sherwin-Williams Company', koreanName: '셔윈 윌리엄즈 (페인트/코팅 1위)', industry: '건축/산업용도료', targetPe: 28 },
  { country: 'US', ticker: 'FCX', name: 'Freeport-McMoRan Inc.', koreanName: '프리포트 맥모란 (글로벌 1위 구리광산)', industry: '구리/금광산채굴', targetPe: 20 },
  { country: 'US', ticker: 'NEM', name: 'Newmont Corporation', koreanName: '뉴몬트 (글로벌 1위 금광기업)', industry: '금광채굴/귀금속', targetPe: 18 },
  { country: 'US', ticker: 'NUE', name: 'Nucor Corporation', koreanName: '뉴코어 (미국최대전기로철강)', industry: '전기로친환경철강', targetPe: 12 },
  { country: 'US', ticker: 'STLD', name: 'Steel Dynamics Inc.', koreanName: '스틸 다이내믹스', industry: '철강제조/금속재활용', targetPe: 11 },
  { country: 'US', ticker: 'CLF', name: 'Cleveland-Cliffs Inc.', koreanName: '클리블랜드 클리프스 (자동차용철강)', industry: '고로철강/철광석', targetPe: 10 },
  { country: 'US', ticker: 'X', name: 'United States Steel Corp', koreanName: 'US 스틸 (미국철강역사)', industry: '판재류철강제조', targetPe: 10 },
  { country: 'US', ticker: 'ALB', name: 'Albemarle Corporation', koreanName: '앨버말 (글로벌최대리튬소재)', industry: '배터리용수산화리튬', targetPe: 16 },
  { country: 'US', ticker: 'SQM', name: 'Sociedad Química y Minera (ADR)', koreanName: 'SQM (칠레리튬염호광산)', industry: '리튬/특수비료', targetPe: 14 },
  { country: 'US', ticker: 'PLD', name: 'Prologis Inc.', koreanName: '프로로지스 (글로벌 1위 물류센터리츠)', industry: '물류센터/이커머스창고리츠', targetPe: 28 },
  { country: 'US', ticker: 'AMT', name: 'American Tower Corp', koreanName: '아메리칸 타워 (통신타워/데이터센터리츠)', industry: '통신타워인프라리츠', targetPe: 24 },
  { country: 'US', ticker: 'EQIX', name: 'Equinix Inc.', koreanName: '에퀴닉스 (글로벌 1위 데이터센터리츠)', industry: 'AI데이터센터/인터커넥션', targetPe: 30 },
  { country: 'US', ticker: 'DLR', name: 'Digital Realty Trust', koreanName: '디지털 리얼티 (AI데이터센터리츠)', industry: '데이터센터리츠', targetPe: 26 },
  { country: 'US', ticker: 'CCI', name: 'Crown Castle Inc.', koreanName: '크라운 캐슬 (미국통신타워/스몰셀)', industry: '무선통신타워리츠', targetPe: 18 },
  { country: 'US', ticker: 'O', name: 'Realty Income Corp', koreanName: '리얼티 인컴 (월배당리츠 대명사)', industry: '월배당/상업용부동산리츠', targetPe: 16 },
  { country: 'US', ticker: 'SPG', name: 'Simon Property Group', koreanName: '사이먼 프로퍼티 그룹 (프리미엄아울렛/쇼핑몰)', industry: '쇼핑몰/아울렛리츠', targetPe: 15 },
  { country: 'US', ticker: 'VICI', name: 'VICI Properties Inc.', koreanName: 'VICI 프로퍼티스 (라스베이거스카지노리츠)', industry: '카지노/엔터테인먼트리츠', targetPe: 14 },
  { country: 'US', ticker: 'PSA', name: 'Public Storage', koreanName: '퍼블릭 스토리지 (셀프스토리지 1위)', industry: '개인창고임대리츠', targetPe: 20 },
  { country: 'US', ticker: 'AVB', name: 'AvalonBay Communities', koreanName: '아발론베이 커뮤니티 (고급아파트임대리츠)', industry: '주거용아파트리츠', targetPe: 20 },
  { country: 'US', ticker: 'EQR', name: 'Equity Residential', koreanName: '에쿼티 레지덴셜', industry: '도심형아파트리츠', targetPe: 20 },
  { country: 'US', ticker: 'WELL', name: 'Welltower Inc.', koreanName: '웰타워 (시니어하우징/실버케어리츠)', industry: '실버타운/헬스케어리츠', targetPe: 30 },
  { country: 'US', ticker: 'VTR', name: 'Ventas Inc.', koreanName: '벤타스 (요양병원/시니어케어)', industry: '시니어하우징리츠', targetPe: 25 },
  { country: 'US', ticker: 'MPW', name: 'Medical Properties Trust', koreanName: '메디컬 프로퍼티스 (병원부동산리츠)', industry: '종합병원리츠/고배당', targetPe: 10 },
  { country: 'US', ticker: 'IRM', name: 'Iron Mountain Inc.', koreanName: '아이언 마운틴 (문서보관/데이터센터리츠)', industry: '데이터보관/디지털스토리지', targetPe: 22 },
  { country: 'US', ticker: 'DHI', name: 'D.R. Horton Inc.', koreanName: 'D.R. 호튼 (미국 1위 주택건설사)', industry: '단독주택건설/분양', targetPe: 12 },
  { country: 'US', ticker: 'LEN', name: 'Lennar Corporation', koreanName: '레나 (미국대형주택건설사)', industry: '주택개발/건설', targetPe: 12 },
  { country: 'US', ticker: 'NVR', name: 'NVR Inc.', koreanName: 'NVR (고수익주택건설)', industry: '프리미엄주택건설', targetPe: 15 },
  { country: 'US', ticker: 'PHM', name: 'PulteGroup Inc.', koreanName: '풀티그룹', industry: '맞춤형주택건설', targetPe: 11 },
  { country: 'US', ticker: 'TOL', name: 'Toll Brothers Inc.', koreanName: '톨 브라더스 (럭셔리주택건설)', industry: '고급주택건설', targetPe: 12 },

  // 7. Popular ETFs & Major Index Funds (20)
  { country: 'US', ticker: 'SPY', name: 'SPDR S&P 500 ETF Trust', koreanName: 'SPY (S&P 500 대표 ETF)', industry: '지수추종ETF', targetPe: 22 },
  { country: 'US', ticker: 'QQQ', name: 'Invesco QQQ Trust', koreanName: 'QQQ (나스닥 100 대표 ETF)', industry: '나스닥ETF', targetPe: 28 },
  { country: 'US', ticker: 'VOO', name: 'Vanguard S&P 500 ETF', koreanName: 'VOO (뱅가드 S&P 500)', industry: '인덱스펀드ETF', targetPe: 22 },
  { country: 'US', ticker: 'VTI', name: 'Vanguard Total Stock Market ETF', koreanName: 'VTI (미국전체시장ETF)', industry: '전체시장ETF', targetPe: 22 },
  { country: 'US', ticker: 'DIA', name: 'SPDR Dow Jones Industrial Average', koreanName: 'DIA (다우존스 30 ETF)', industry: '다우존스ETF', targetPe: 18 },
  { country: 'US', ticker: 'IWM', name: 'iShares Russell 2000 ETF', koreanName: 'IWM (러셀 2000 중소형주)', industry: '중소형주ETF', targetPe: 16 },
  { country: 'US', ticker: 'SCHD', name: 'Schwab U.S. Dividend Equity ETF', koreanName: 'SCHD (슈드 / 미국배당다우존스)', industry: '고배당성장ETF', targetPe: 16 },
  { country: 'US', ticker: 'JEPI', name: 'JPMorgan Equity Premium Income ETF', koreanName: 'JEPI (JP모건 월배당커버드콜)', industry: '월배당커버드콜ETF', targetPe: 15 },
  { country: 'US', ticker: 'JEPQ', name: 'JPMorgan Nasdaq Equity Premium ETF', koreanName: 'JEPQ (나스닥 100 월배당커버드콜)', industry: '월배당나스닥ETF', targetPe: 20 },
  { country: 'US', ticker: 'SOXL', name: 'Direxion Daily Semiconductor Bull 3X', koreanName: 'SOXL (필라델피아반도체 3배 레버리지)', industry: '반도체3배레버리지', targetPe: 30 },
  { country: 'US', ticker: 'TQQQ', name: 'ProShares UltraPro QQQ', koreanName: 'TQQQ (나스닥 100 3배 레버리지)', industry: '나스닥3배레버리지', targetPe: 30 },
  { country: 'US', ticker: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF', koreanName: 'TLT (미국 20년이상 장기국채)', industry: '미국장기채권ETF', targetPe: 15 },
  { country: 'US', ticker: 'SMH', name: 'VanEck Semiconductor ETF', koreanName: 'SMH (반도체대표ETF)', industry: '반도체ETF', targetPe: 32 },
  { country: 'US', ticker: 'XLK', name: 'Technology Select Sector SPDR', koreanName: 'XLK (미국테크섹터ETF)', industry: '테크ETF', targetPe: 30 },
  { country: 'US', ticker: 'XLF', name: 'Financial Select Sector SPDR', koreanName: 'XLF (미국금융섹터ETF)', industry: '금융ETF', targetPe: 14 },
  { country: 'US', ticker: 'XLE', name: 'Energy Select Sector SPDR', koreanName: 'XLE (미국에너지섹터ETF)', industry: '에너지ETF', targetPe: 13 },
  { country: 'US', ticker: 'XLV', name: 'Health Care Select Sector SPDR', koreanName: 'XLV (미국헬스케어섹터ETF)', industry: '헬스케어ETF', targetPe: 18 },
  { country: 'US', ticker: 'VNQ', name: 'Vanguard Real Estate ETF', koreanName: 'VNQ (미국부동산리츠ETF)', industry: '리츠ETF', targetPe: 20 },
  { country: 'US', ticker: 'GLD', name: 'SPDR Gold Shares', koreanName: 'GLD (금현물 ETF)', industry: '금현물원자재ETF', targetPe: 15 },
  { country: 'US', ticker: 'SLV', name: 'iShares Silver Trust', koreanName: 'SLV (은현물 ETF)', industry: '은현물원자재ETF', targetPe: 15 },

  // 8. Global Tech ADRs & High-Growth Innovators (35)
  { country: 'US', ticker: 'BABA', name: 'Alibaba Group Holding (ADR)', koreanName: '알리바바 (이커머스/클라우드)', industry: '이커머스/AI클라우드', targetPe: 12 },
  { country: 'US', ticker: 'PDD', name: 'PDD Holdings Inc. (Temu)', koreanName: '핀둬둬 (테무 Temu 모회사)', industry: '크로스보더이커머스', targetPe: 15 },
  { country: 'US', ticker: 'JD', name: 'JD.com Inc. (ADR)', koreanName: '징둥닷컴', industry: '직영이커머스/물류', targetPe: 10 },
  { country: 'US', ticker: 'BIDU', name: 'Baidu Inc. (ADR)', koreanName: '바이두 (중국AI/자율주행 아폴로)', industry: 'AI/자율주행/검색', targetPe: 12 },
  { country: 'US', ticker: 'NTES', name: 'NetEase Inc. (ADR)', koreanName: '넷이즈 (게임/엔터)', industry: '온라인게임/엔터테인먼트', targetPe: 15 },
  { country: 'US', ticker: 'SE', name: 'Sea Limited (Shopee/Garena)', koreanName: '씨리미티드 (동남아 쇼피/가레나)', industry: '동남아이커머스/게임/핀테크', targetPe: 25 },
  { country: 'US', ticker: 'GRAB', name: 'Grab Holdings Limited', koreanName: '그랩 (동남아 슈퍼앱)', industry: '동남아모빌리티/배달/금융', targetPe: 28 },
  { country: 'US', ticker: 'MELI', name: 'MercadoLibre Inc.', koreanName: '메르카도리브레 (남미의 아마존)', industry: '중남미이커머스/핀테크', targetPe: 35 },
  { country: 'US', ticker: 'NU', name: 'Nu Holdings Ltd. (Nubank)', koreanName: '누뱅크 (워렌버핏남미디지털은행)', industry: '중남미디지털뱅킹', targetPe: 28 },
  { country: 'US', ticker: 'SHOP', name: 'Shopify Inc.', koreanName: '쇼피파이 (글로벌 D2C 쇼핑몰솔루션)', industry: '이커머스플랫폼', targetPe: 45 },
  { country: 'US', ticker: 'RBLX', name: 'Roblox Corporation', koreanName: '로블록스 (메타버스/게임)', industry: '메타버스/온라인게임플랫폼', targetPe: 35 },
  { country: 'US', ticker: 'U', name: 'Unity Software Inc.', koreanName: '유니티 소프트웨어 (3D게임엔진)', industry: '실시간3D인터랙티브엔진', targetPe: 30 },
  { country: 'US', ticker: 'ZM', name: 'Zoom Video Communications', koreanName: '줌 비디오 (화상회의)', industry: '통합비디오커뮤니케이션', targetPe: 18 },
  { country: 'US', ticker: 'DOCU', name: 'DocuSign Inc.', koreanName: '도큐사인 (전자서명 1위)', industry: '전자서명/계약클라우드', targetPe: 22 },
  { country: 'US', ticker: 'TWLO', name: 'Twilio Inc.', koreanName: '트윌리오 (클라우드통신API)', industry: '고객인게이지먼트플랫폼', targetPe: 25 },
  { country: 'US', ticker: 'OKTA', name: 'Okta Inc.', koreanName: '옥타 (클라우드아이덴티티인증보안)', industry: '신원인증/IAM보안', targetPe: 30 },
  { country: 'US', ticker: 'AXON', name: 'Axon Enterprise Inc.', koreanName: '액손 엔터프라이즈 (테이저건/바디캠)', industry: '경찰공공안전테크', targetPe: 45 },
  { country: 'US', ticker: 'CPRT', name: 'Copart Inc.', koreanName: '코파트 (온라인차량경매)', industry: '차량경매/재활용', targetPe: 28 },
  { country: 'US', ticker: 'FAST', name: 'Fastenal Company', koreanName: '패스널 (산업용파스너/자재)', industry: '산업용패스너/소모품유통', targetPe: 28 },
  { country: 'US', ticker: 'PCAR', name: 'PACCAR Inc', koreanName: '패카 (켄워스/피터빌트 대형트럭)', industry: '상용차/대형디젤트럭', targetPe: 14 },
  { country: 'US', ticker: 'WAB', name: 'Westinghouse Air Brake (Wabtec)', koreanName: '웹텍 (철도기관차/신호제어)', industry: '철도엔지니어링/기관차', targetPe: 24 },
  { country: 'US', ticker: 'TDG', name: 'TransDigm Group Inc.', koreanName: '트랜스다임 그룹 (항공기독점부품)', industry: '항공기애프터마켓부품', targetPe: 32 },
  { country: 'US', ticker: 'HII', name: 'Huntington Ingalls Industries', koreanName: '헌팅턴 잉걸스 (핵잠수함/항공모함)', industry: '군용함정/핵잠수함건조', targetPe: 16 },
  { country: 'US', ticker: 'MSCI', name: 'MSCI Inc.', koreanName: 'MSCI (글로벌주가지수/ESG평가)', industry: '벤치마크지수/투자분석', targetPe: 32 },
  { country: 'US', ticker: 'AON', name: 'Aon plc', koreanName: '에이온 (글로벌보험중개/컨설팅)', industry: '보험중개/리스크컨설팅', targetPe: 22 },
  { country: 'US', ticker: 'MMC', name: 'Marsh & McLennan Companies', koreanName: '마시 앤 맥레넌', industry: '글로벌위험관리/인사컨설팅', targetPe: 24 },
  { country: 'US', ticker: 'WTW', name: 'Willis Towers Watson', koreanName: '윌리스 타워스 왓슨', industry: '보험중개/기업컨설팅', targetPe: 18 },
  { country: 'US', ticker: 'GWW', name: 'W.W. Grainger Inc.', koreanName: '그레인저 (산업용MRO유통)', industry: 'MRO소모자재유통', targetPe: 24 },
  { country: 'US', ticker: 'TSCO', name: 'Tractor Supply Company', koreanName: '트랙터 서플라이 (농촌라이프스타일유통)', industry: '농촌생활용품유통', targetPe: 22 },
  { country: 'US', ticker: 'ORLY', name: 'O\'Reilly Automotive Inc.', koreanName: '오라일리 오토모티브 (자동차애프터마켓부품)', industry: '자동차유지보수부품', targetPe: 26 },
  { country: 'US', ticker: 'AZO', name: 'AutoZone Inc.', koreanName: '오토존 (자동차자가정비부품)', industry: '자동차부품소매체인', targetPe: 20 },
  { country: 'US', ticker: 'CTVA', name: 'Corteva Inc.', koreanName: '코르테바 (듀폰농업/종자/작물보호)', industry: '종자/작물보호제농업과학', targetPe: 22 },
  { country: 'US', ticker: 'FMC', name: 'FMC Corporation', koreanName: 'FMC (작물보호농약)', industry: '농업화학/살충제', targetPe: 12 },
  { country: 'US', ticker: 'MOS', name: 'The Mosaic Company', koreanName: '모자이크 (인산염/칼륨비료)', industry: '비료광산/농업원자재', targetPe: 10 },
  { country: 'US', ticker: 'CF', name: 'CF Industries Holdings', koreanName: 'CF 인더스트리스 (질소비료/청정암모니아)', industry: '질소비료/수소암모니아', targetPe: 11 },

  // 9. Additional S&P 500 Core, Tech & Healthcare Leaders (140)
  { country: 'US', ticker: 'CPNG', name: 'Coupang Inc.', koreanName: '쿠팡 (로켓배송/이커머스)', industry: '이커머스/풀필먼트', targetPe: 30 },
  { country: 'US', ticker: 'CHWY', name: 'Chewy Inc.', koreanName: '츄이 (반려동물용품이커머스)', industry: '반려동물소비재', targetPe: 25 },
  { country: 'US', ticker: 'BBY', name: 'Best Buy Co. Inc.', koreanName: '베스트바이 (전자제품유통)', industry: '가전소매유통', targetPe: 13 },
  { country: 'US', ticker: 'WSM', name: 'Williams-Sonoma Inc.', koreanName: '윌리엄스 소노마 (포터리반/홈퍼니싱)', industry: '홈퍼니싱/가구', targetPe: 16 },
  { country: 'US', ticker: 'BURL', name: 'Burlington Stores', koreanName: '벌링턴 스토어', industry: '할인패션유통', targetPe: 24 },
  { country: 'US', ticker: 'FIVE', name: 'Five Below Inc.', koreanName: '파이브 빌로우 (10대소비재)', industry: '초저가유통', targetPe: 22 },
  { country: 'US', ticker: 'DRI', name: 'Darden Restaurants', koreanName: '다든 레스토랑 (올리브가든/롱혼)', industry: '패밀리레스토랑외식', targetPe: 18 },
  { country: 'US', ticker: 'KMX', name: 'CarMax Inc.', koreanName: '카맥스 (미국 1위 중고차유통)', industry: '중고차소매유통', targetPe: 18 },
  { country: 'US', ticker: 'GPC', name: 'Genuine Parts Company', koreanName: '제뉴인 파츠 (NAPA 자동차부품)', industry: '자동차/산업부품유통', targetPe: 16 },
  { country: 'US', ticker: 'LKQ', name: 'LKQ Corporation', koreanName: 'LKQ (재생자동차부품)', industry: '자동차애프터마켓부품', targetPe: 13 },
  { country: 'US', ticker: 'BDX', name: 'Becton Dickinson and Co.', koreanName: '벡톤 디킨슨 (BD 주사기/의료소모품)', industry: '의료기기/소모품', targetPe: 18 },
  { country: 'US', ticker: 'COO', name: 'The Cooper Companies', koreanName: '쿠퍼컴퍼니 (쿠퍼비전 콘택트렌즈)', industry: '콘택트렌즈/여성건강', targetPe: 24 },
  { country: 'US', ticker: 'STE', name: 'STERIS plc', koreanName: '스테리스 (수술실멸균솔루션)', industry: '멸균/수술장비', targetPe: 22 },
  { country: 'US', ticker: 'HOLX', name: 'Hologic Inc.', koreanName: '홀로직 (유방암검진 맘모그래피)', industry: '여성건강/체외진단', targetPe: 18 },
  { country: 'US', ticker: 'TECH', name: 'Bio-Techne Corp', koreanName: '바이오테크네 (생명과학시약)', industry: '바이오시약/연구기기', targetPe: 30 },
  { country: 'US', ticker: 'BIO', name: 'Bio-Rad Laboratories', koreanName: '바이오라드 (임상진단장비)', industry: '생명공학연구/진단', targetPe: 25 },
  { country: 'US', ticker: 'IQV', name: 'IQVIA Holdings Inc.', koreanName: '아이큐비아 (글로벌 1위 임상시험 CRO)', industry: '임상시험수탁/헬스케어데이터', targetPe: 20 },
  { country: 'US', ticker: 'CRL', name: 'Charles River Laboratories', koreanName: '찰스리버 라보라토리스 (전임상연구)', industry: '신약개발전임상CRO', targetPe: 18 },
  { country: 'US', ticker: 'WST', name: 'West Pharmaceutical Services', koreanName: '웨스트 파마슈티컬 (주사기바이알패키징)', industry: '주사제패키징/약물전달', targetPe: 35 },
  { country: 'US', ticker: 'RGEN', name: 'Repligen Corporation', koreanName: '레플리젠 (바이오프로세싱소재)', industry: '바이오의약품정제소재', targetPe: 40 },
  { country: 'US', ticker: 'EXAS', name: 'Exact Sciences Corp', koreanName: '이그젝트 사이언시스 (대장암조기진단 콜로가드)', industry: '암조기진단/액체생검', targetPe: 35 },
  { country: 'US', ticker: 'NTRA', name: 'Natera Inc.', koreanName: '나테라 (비침습산전검사 NIPT)', industry: '유전체진단/액체생검', targetPe: 40 },
  { country: 'US', ticker: 'VEEV', name: 'Veeva Systems Inc.', koreanName: '비바 시스템즈 (제약바이오클라우드CRM)', industry: '제약특화클라우드', targetPe: 35 },
  { country: 'US', ticker: 'GWRE', name: 'Guidewire Software', koreanName: '가이드와이어 (보험클라우드코어)', industry: '보험사전산코어SW', targetPe: 40 },
  { country: 'US', ticker: 'IOT', name: 'Samsara Inc.', koreanName: '삼사라 (산업IoT/커넥티드플릿)', industry: '산업IoT/플릿관리', targetPe: 45 },
  { country: 'US', ticker: 'QRVO', name: 'Qorvo Inc.', koreanName: '코보 (RF통신반도체)', industry: 'RF통신모듈', targetPe: 15 },
  { country: 'US', ticker: 'SWKS', name: 'Skyworks Solutions', koreanName: '스카이웍스 솔루션즈 (스마트폰RF)', industry: 'RF통신반도체', targetPe: 14 },
  { country: 'US', ticker: 'CRUS', name: 'Cirrus Logic Inc.', koreanName: '시러스 로직 (애플오디오반도체)', industry: '오디오코덱/전력반도체', targetPe: 16 },
  { country: 'US', ticker: 'POWI', name: 'Power Integrations', koreanName: '파워 인티그레이션스 (고효율전력반도체)', industry: 'GaN전력반도체', targetPe: 25 },
  { country: 'US', ticker: 'RMBS', name: 'Rambus Inc.', koreanName: '램버스 (초고속메모리인터페이스)', industry: 'DDR5/HBM인터페이스', targetPe: 30 },
  { country: 'US', ticker: 'ACLS', name: 'Axcelis Technologies', koreanName: '엑셀리스 (이온주입장비)', industry: '반도체이온주입장비', targetPe: 18 },
  { country: 'US', ticker: 'LSCC', name: 'Lattice Semiconductor', koreanName: '래티스 세미컨덕터 (저전력FPGA)', industry: 'FPGA반도체', targetPe: 30 },
  { country: 'US', ticker: 'CYBR', name: 'CyberArk Software', koreanName: '사이버아크 (특권계정관리 PAM보안)', industry: '계정권한보안', targetPe: 45 },
  { country: 'US', ticker: 'TENB', name: 'Tenable Holdings', koreanName: '테너블 (취약점진단 네서스)', industry: '사이버보안취약점분석', targetPe: 30 },
  { country: 'US', ticker: 'FITB', name: 'Fifth Third Bancorp', koreanName: '피프스 써드 뱅코프', industry: '중서부지역은행', targetPe: 11 },
  { country: 'US', ticker: 'HBAN', name: 'Huntington Bancshares', koreanName: '헌팅턴 뱅크셰어스', industry: '지역상업은행', targetPe: 11 },
  { country: 'US', ticker: 'RF', name: 'Regions Financial Corp', koreanName: '리전스 파이낸셜', industry: '동남부지역은행', targetPe: 10 },
  { country: 'US', ticker: 'KEY', name: 'KeyCorp', koreanName: '키코프 (키뱅크)', industry: '지역상업은행', targetPe: 11 },
  { country: 'US', ticker: 'CFG', name: 'Citizens Financial Group', koreanName: '시티즌스 파이낸셜', industry: '동북부상업은행', targetPe: 11 },
  { country: 'US', ticker: 'MTB', name: 'M&T Bank Corporation', koreanName: 'M&T 뱅크', industry: '우량상업은행', targetPe: 12 },
  { country: 'US', ticker: 'NTRS', name: 'Northern Trust Corp', koreanName: '노던 트러스트 (수탁/WM)', industry: '부유층자산관리/수탁', targetPe: 13 },
  { country: 'US', ticker: 'ZION', name: 'Zions Bancorporation', koreanName: '자이언스 뱅코퍼레이션', industry: '서부지역은행', targetPe: 11 },
  { country: 'US', ticker: 'CMA', name: 'Comerica Incorporated', koreanName: '코메리카', industry: '기업상업은행', targetPe: 10 },
  { country: 'US', ticker: 'ALLY', name: 'Ally Financial Inc.', koreanName: '앨라이 파이낸셜 (온라인은행/오토론)', industry: '디지털뱅킹/자동차금융', targetPe: 9 },
  { country: 'US', ticker: 'DOW', name: 'Dow Inc.', koreanName: '다우 (글로벌화학소재)', industry: '기초화학/플라스틱', targetPe: 14 },
  { country: 'US', ticker: 'DD', name: 'DuPont de Nemours Inc.', koreanName: '듀폰 (전자재료/케블라/노멕스)', industry: '스페셜티소재/전자재료', targetPe: 18 },
  { country: 'US', ticker: 'PPG', name: 'PPG Industries Inc.', koreanName: 'PPG 인더스트리스 (자동차/항공페인트)', industry: '특수코팅도료', targetPe: 18 },
  { country: 'US', ticker: 'CE', name: 'Celanese Corporation', koreanName: '셀라니즈 (엔지니어링플라스틱)', industry: '스페셜티화학소재', targetPe: 12 },
  { country: 'US', ticker: 'EMN', name: 'Eastman Chemical Company', koreanName: '이스트만 케미컬 (트라이탄소재)', industry: '특수플라스틱/화학', targetPe: 12 },
  { country: 'US', ticker: 'RPM', name: 'RPM International Inc.', koreanName: 'RPM 인터내셔널 (방수/실란트)', industry: '건축/특수코팅재', targetPe: 20 },
  { country: 'US', ticker: 'LYB', name: 'LyondellBasell Industries', koreanName: '라이온델바젤 (폴리올레핀/고배당)', industry: '석유화학/플라스틱', targetPe: 10 },
  { country: 'US', ticker: 'VMC', name: 'Vulcan Materials Company', koreanName: '벌칸 머티리얼즈 (골재/아스팔트 1위)', industry: '도로인프라건설골재', targetPe: 28 },
  { country: 'US', ticker: 'MLM', name: 'Martin Marietta Materials', koreanName: '마틴 마리에타 (시멘트/골재)', industry: '건축골재/중장비인프라', targetPe: 26 },
  { country: 'US', ticker: 'D', name: 'Dominion Energy Inc.', koreanName: '도미니언 에너지 (버지니아데이터센터전력)', industry: '데이터센터전력유틸리티', targetPe: 16 },
  { country: 'US', ticker: 'PEG', name: 'Public Service Enterprise Group', koreanName: 'PSEG (뉴저지전력/원자력)', industry: '원자력발전/전력망', targetPe: 16 },
  { country: 'US', ticker: 'WEC', name: 'WEC Energy Group', koreanName: 'WEC 에너지 (위스콘신전력)', industry: '전력가스유틸리티', targetPe: 16 },
  { country: 'US', ticker: 'ES', name: 'Eversource Energy', koreanName: '에버소스 에너지 (뉴잉글랜드전력)', industry: '송배전전력망', targetPe: 15 },
  { country: 'US', ticker: 'DTE', name: 'DTE Energy Company', koreanName: 'DTE 에너지 (미시간전력)', industry: '전력가스유틸리티', targetPe: 16 },
  { country: 'US', ticker: 'PPL', name: 'PPL Corporation', koreanName: 'PPL 코퍼레이션 (펜실베이니아/켄터키전력)', industry: '규제전력유틸리티', targetPe: 15 },
  { country: 'US', ticker: 'ETR', name: 'Entergy Corporation', koreanName: '엔터지 (걸프만원자력/전력)', industry: '원자력발전/전력', targetPe: 15 },
  { country: 'US', ticker: 'FE', name: 'FirstEnergy Corp.', koreanName: '퍼스트에너지 (오하이오/펜실베이니아송전망)', industry: '송배전전력유틸리티', targetPe: 14 },
  { country: 'US', ticker: 'CMS', name: 'CMS Energy Corporation', koreanName: 'CMS 에너지 (컨슈머스에너지)', industry: '전력/청정에너지', targetPe: 16 },
  { country: 'US', ticker: 'CNP', name: 'CenterPoint Energy', koreanName: '센터포인트 에너지 (휴스턴전력인프라)', industry: '송배전전력망', targetPe: 15 },
  { country: 'US', ticker: 'NI', name: 'NiSource Inc.', koreanName: '나이사우스 (천연가스공급)', industry: '천연가스유틸리티', targetPe: 16 },
  { country: 'US', ticker: 'LNT', name: 'Alliant Energy Corp', koreanName: '얼라이언트 에너지', industry: '신재생전력유틸리티', targetPe: 16 },
  { country: 'US', ticker: 'EVRG', name: 'Evergy Inc.', koreanName: '에버지 (캔자스/미주리전력)', industry: '전력유틸리티', targetPe: 15 },
  { country: 'US', ticker: 'ATO', name: 'Atmos Energy Corporation', koreanName: '애트모스 에너지 (순수천연가스배당주)', industry: '천연가스유통배당주', targetPe: 18 },
  { country: 'US', ticker: 'OKE', name: 'ONEOK Inc.', koreanName: '원오케이 (천연가스액체 NGL 미드스트림)', industry: '천연가스미드스트림인프라', targetPe: 16 },
  { country: 'US', ticker: 'TRGP', name: 'Targa Resources Corp', koreanName: '타르가 리소스 (NGL/LPG수출)', industry: '에너지미드스트림/수출', targetPe: 20 },
  { country: 'US', ticker: 'ITT', name: 'ITT Inc.', koreanName: 'ITT (항공브레이크/산업용펌프)', industry: '특수기계부품', targetPe: 22 },
  { country: 'US', ticker: 'DOV', name: 'Dover Corporation', koreanName: '도버 (산업자동화/냉동시스템)', industry: '복합엔지니어링장비', targetPe: 20 },
  { country: 'US', ticker: 'FTV', name: 'Fortive Corporation', koreanName: '포티브 (정밀계측/소프트웨어)', industry: '스마트공장/정밀계측', targetPe: 22 },
  { country: 'US', ticker: 'GGG', name: 'Graco Inc.', koreanName: '그라코 (유체이송도장장비)', industry: '유체핸들링장비', targetPe: 25 },
  { country: 'US', ticker: 'HUBB', name: 'Hubbell Incorporated', koreanName: '허벨 (송배전전력인프라부품)', industry: '전력그리드기자재', targetPe: 25 },
  { country: 'US', ticker: 'AOS', name: 'A. O. Smith Corp', koreanName: 'A.O. 스미스 (온수기/수처리필터)', industry: '친환경온수기/보일러', targetPe: 20 },
  { country: 'US', ticker: 'LECO', name: 'Lincoln Electric Holdings', koreanName: '링컨 일렉트릭 (용접기/로봇용접)', industry: '자동화용접솔루션', targetPe: 22 },
  { country: 'US', ticker: 'TREX', name: 'Trex Company Inc.', koreanName: '트렉스 (친환경합성목재데크)', industry: '친환경건축자재', targetPe: 28 },
  { country: 'US', ticker: 'BLDR', name: 'Builders FirstSource', koreanName: '빌더스 퍼스트소스 (주택건축자재 1위)', industry: '주택건축자재제조유통', targetPe: 14 },
  { country: 'US', ticker: 'J', name: 'Jacobs Solutions Inc.', koreanName: '제이콥스 (글로벌인프라엔지니어링)', industry: '첨단인프라설계/우주컨설팅', targetPe: 20 }
];

// Combine all into unified catalog
const fullCatalog = [...nonUsStocks, ...usCatalog];

fs.writeFileSync(catalogPath, JSON.stringify(fullCatalog, null, 2), 'utf8');

console.log('Successfully updated US Catalog:');
console.log('KR:', fullCatalog.filter(s => s.country === 'KR').length);
console.log('VN:', fullCatalog.filter(s => s.country === 'VN').length);
console.log('CN:', fullCatalog.filter(s => s.country === 'CN').length);
console.log('US:', fullCatalog.filter(s => s.country === 'US').length);
console.log('Grand Total:', fullCatalog.length);
