import { initializeApp, cert } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';

const serviceAccount = {
  "type": "service_account",
  "project_id": "stocktemp-c7d77",
  "private_key_id": "deaebf7a50fe051e7194bc48cbc3e5ad9390f3e2",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDCerLs7EpmRBTy\nCIjCqTGsLBez8HHSWiRcHFC7r5Zk2Nzv6QuAvVMa7CBKNMp0fymykF1z5Hyk9YVI\nIeL/9SOomhDa09yPqgcvcfzxR9RaQZIjYhbrjBi7IYGiMvrBQELvzdcbAqP40DoU\nZ+CG+7dYEGDFiZfj38mqivKu0BnpHjBQURD/NA9D+zbZ+UN6Gt4PYdPmEKVA0e6B\nvXdT1H1/LXlieUKOYyFnKx4Yn0qTlOUq2zpZ8Bkusnvx9EUOxqoS7Uix+SP/G+Uy\n+TI3avFH+SFKMn3XF+7RTengcQkPDR5MtiuA0IYx4X9ssgk+vRWfQEU72mHdrU/G\nIymM1AzJAgMBAAECggEAMkuzPGy7rQkMda/ZVqaVLxbUJngXp7QiVSQJiRCXD4u6\nT91wWSIdfQf2LdrLRSeh7AlD8fX0emD40DfbUiDe0PrPQxipoQnzA8UyCmBuPc1Z\ncwcqME6yEqtOsFkI2rO42/XbHKQpLe8EJkTbH2238/GAZXX5LziwGggHTUiKeuwc\n0n1XF61Em/bmr7fpUURC+G0gSY8p4hxuUOGaGqgGTqZxiUvaX18t73WNIfphRK1Q\nTtRasBazMnqCyl0DrfSq9M1NhHyy9I3/4NDRXAKI7u3fZ8qLNbfwvV4B+4Q5C3ic\n9tZFvbOIusE9y235XoJpljPf5uu46pNBXo+qAIWspQKBgQD1/Sr+fsxzu+1YYx0K\nzMPyWIm4qH3hI7B7icTzb1T4fRJryBkQ0L2/flzFYKxVdehxp4kKJCeL/iLvujy+\n7KQMoAQTHxbzoRGJsP+4aYcrLOmhG1Lnm6R/b6E8ThYjv7fZ+HU2aR71Zl0Xjhgo\nPqlHSr157p5sP9pG1JvAnBUHHwKBgQDKZODm0fYr0VjKcSRQGdbCMpsipXPm0aaK\UJ5Ay80I14+jnwl8iHib8egPWYpbjSIkk5vAtGVAq2B6qyVI+iY5664C5w49s1Gw\nED615B/nfnLdozDsL5eG7JsuoO1tdpQrR5fIR2skxA5jiiRqxd6MHpEr9MZkLJ3D\nc72/AD93FwKBgAM1jVUKpHIyFnObv2o/p6LGwu00zYedZpUGBBrE7g/b2dysHJ+a\niY8w/9bXXwgyZJju/ZuzQwzRgPUtsdMv1SgRAlyZgDwncsogFAX84nWOvXGLoLZC\n0o+TDkByKFnJC4X9dtIB5xR+hGJlSS1lO+IhOH2ZvlldL+TSq0GFB8UzAoGALDSA\nUqnFJKjixcSUc9JQ77Vx4M1WVTGxOECHcAuTSr0aKFiSD9sWzKi3ULLz3y8iJ+79\nc8dy3f8QYXqD+D56nuf057ljiOJjkxrZN40N0tfxaqs8Ajoa1GNVOYf4k5H0psdK\nRXoj0rHnmqIPdiqlguEiQAGEW1jLVGcxKEh7lB0CgYAxeyz+VQeRaTbkSShOx2GT\nIgihg0pvRMCtSbSQfvOC0mEWInhQVxOdKtuED5FgHUoeD8kEj9OlIbiwhwfjRYN2\nMjjwxAND3EXUdtBwYyfl+va7S96qyFa9Yv0jvFl/gOnWc7Xn//CML1nWlQTL2JRY\nks6nZMacuB/tXy0rSVIThw==\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-fbsvc@stocktemp-c7d77.iam.gserviceaccount.com",
  "client_id": "103148109688850996587",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40stocktemp-c7d77.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
};

initializeApp({
  credential: cert(serviceAccount)
});

const db = getFirestore();

const MOCK_STOCKS = [
  // ================= KOREA (KR) =================
  {
    id: 'KR_067160',
    ticker: '067160',
    name: 'SOOP (AfreecaTV)',
    koreanName: '숲 (아프리카TV)',
    country: 'KR',
    industry: '양방향미디어와서비스',
    eps: 8175,
    currentPrice: 98500,
    currency: '₩',
    defaultTargetPe: 14,
    tradingViewSymbol: 'KRX:067160',
    naverTicker: '067160',
  },
  {
    id: 'KR_376300',
    ticker: '376300',
    name: 'DearU',
    koreanName: '디어유',
    country: 'KR',
    industry: '양방향미디어와서비스',
    eps: 1530,
    currentPrice: 24800,
    currency: '₩',
    defaultTargetPe: 14,
    tradingViewSymbol: 'KRX:376300',
    naverTicker: '376300',
  },
  {
    id: 'KR_035420',
    ticker: '035420',
    name: 'NAVER',
    koreanName: '네이버',
    country: 'KR',
    industry: '양방향미디어와서비스',
    eps: 13293,
    currentPrice: 172000,
    currency: '₩',
    defaultTargetPe: 16,
    tradingViewSymbol: 'KRX:035420',
    naverTicker: '035420',
  },
  {
    id: 'KR_035720',
    ticker: '035720',
    name: 'Kakao',
    koreanName: '카카오',
    country: 'KR',
    industry: '양방향미디어와서비스',
    eps: 788,
    currentPrice: 38550,
    currency: '₩',
    defaultTargetPe: 18,
    tradingViewSymbol: 'KRX:035720',
    naverTicker: '035720',
  },
  {
    id: 'KR_005930',
    ticker: '005930',
    name: 'Samsung Electronics',
    koreanName: '삼성전자',
    country: 'KR',
    industry: '반도체및반도체장비',
    eps: 3240,
    currentPrice: 78200,
    currency: '₩',
    defaultTargetPe: 15,
    tradingViewSymbol: 'KRX:005930',
    naverTicker: '005930',
  },
  {
    id: 'KR_000660',
    ticker: '000660',
    name: 'SK Hynix',
    koreanName: 'SK하이닉스',
    country: 'KR',
    industry: '반도체및반도체장비',
    eps: 6850,
    currentPrice: 198000,
    currency: '₩',
    defaultTargetPe: 15,
    tradingViewSymbol: 'KRX:000660',
    naverTicker: '000660',
  },
  {
    id: 'KR_005380',
    ticker: '005380',
    name: 'Hyundai Motor',
    koreanName: '현대자동차',
    country: 'KR',
    industry: '자동차',
    eps: 42100,
    currentPrice: 245000,
    currency: '₩',
    defaultTargetPe: 7,
    tradingViewSymbol: 'KRX:005380',
    naverTicker: '005380',
  },
  {
    id: 'KR_000270',
    ticker: '000270',
    name: 'Kia Corp',
    koreanName: '기아',
    country: 'KR',
    industry: '자동차',
    eps: 28900,
    currentPrice: 112000,
    currency: '₩',
    defaultTargetPe: 6,
    tradingViewSymbol: 'KRX:000270',
    naverTicker: '000270',
  },
  {
    id: 'KR_105560',
    ticker: '105560',
    name: 'KB Financial Group',
    koreanName: 'KB금융',
    country: 'KR',
    industry: '은행',
    eps: 11200,
    currentPrice: 85000,
    currency: '₩',
    defaultTargetPe: 8,
    tradingViewSymbol: 'KRX:105560',
    naverTicker: '105560',
  },
  {
    id: 'KR_055550',
    ticker: '055550',
    name: 'Shinhan Financial Group',
    koreanName: '신한지주',
    country: 'KR',
    industry: '은행',
    eps: 8900,
    currentPrice: 56000,
    currency: '₩',
    defaultTargetPe: 7,
    tradingViewSymbol: 'KRX:055550',
    naverTicker: '055550',
  },
  {
    id: 'KR_068270',
    ticker: '068270',
    name: 'Celltrion',
    koreanName: '셀트리온',
    country: 'KR',
    industry: '제약',
    eps: 3850,
    currentPrice: 195000,
    currency: '₩',
    defaultTargetPe: 35,
    tradingViewSymbol: 'KRX:068270',
    naverTicker: '068270',
  },

  // ================= UNITED STATES (US) =================
  {
    id: 'US_AAPL',
    ticker: 'AAPL',
    name: 'Apple Inc.',
    koreanName: '애플',
    country: 'US',
    industry: 'Technology Hardware',
    eps: 6.57,
    currentPrice: 226.50,
    currency: '$',
    defaultTargetPe: 28,
    tradingViewSymbol: 'NASDAQ:AAPL',
    naverTicker: 'AAPL.O',
  },
  {
    id: 'US_TSLA',
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    koreanName: '테슬라',
    country: 'US',
    industry: 'Automotive',
    eps: 2.38,
    currentPrice: 218.40,
    currency: '$',
    defaultTargetPe: 45,
    tradingViewSymbol: 'NASDAQ:TSLA',
    naverTicker: 'TSLA.O',
  },
  {
    id: 'US_NVDA',
    ticker: 'NVDA',
    name: 'NVIDIA Corp.',
    koreanName: '엔비디아',
    country: 'US',
    industry: 'Semiconductors',
    eps: 1.80,
    currentPrice: 128.50,
    currency: '$',
    defaultTargetPe: 40,
    tradingViewSymbol: 'NASDAQ:NVDA',
    naverTicker: 'NVDA.O',
  },
  {
    id: 'US_MSFT',
    ticker: 'MSFT',
    name: 'Microsoft Corp.',
    koreanName: '마이크로소프트',
    country: 'US',
    industry: 'Software',
    eps: 11.80,
    currentPrice: 420.10,
    currency: '$',
    defaultTargetPe: 32,
    tradingViewSymbol: 'NASDAQ:MSFT',
    naverTicker: 'MSFT.O',
  },
  {
    id: 'US_GOOGL',
    ticker: 'GOOGL',
    name: 'Alphabet Inc.',
    koreanName: '알파벳 (구글)',
    country: 'US',
    industry: 'Internet & Services',
    eps: 6.97,
    currentPrice: 165.20,
    currency: '$',
    defaultTargetPe: 24,
    tradingViewSymbol: 'NASDAQ:GOOGL',
    naverTicker: 'GOOGL.O',
  },
  {
    id: 'US_AMZN',
    ticker: 'AMZN',
    name: 'Amazon.com Inc.',
    koreanName: '아마존',
    country: 'US',
    industry: 'Retail & E-commerce',
    eps: 4.18,
    currentPrice: 178.40,
    currency: '$',
    defaultTargetPe: 35,
    tradingViewSymbol: 'NASDAQ:AMZN',
    naverTicker: 'AMZN.O',
  },
  {
    id: 'US_META',
    ticker: 'META',
    name: 'Meta Platforms Inc.',
    koreanName: '메타 (페이스북)',
    country: 'US',
    industry: 'Social Media',
    eps: 19.80,
    currentPrice: 495.30,
    currency: '$',
    defaultTargetPe: 25,
    tradingViewSymbol: 'NASDAQ:META',
    naverTicker: 'META.O',
  },
  {
    id: 'US_NFLX',
    ticker: 'NFLX',
    name: 'Netflix Inc.',
    koreanName: '넷플릭스',
    country: 'US',
    industry: 'Entertainment',
    eps: 17.50,
    currentPrice: 650.00,
    currency: '$',
    defaultTargetPe: 30,
    tradingViewSymbol: 'NASDAQ:NFLX',
    naverTicker: 'NFLX.O',
  },
  {
    id: 'US_AMD',
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    koreanName: 'AMD (반도체)',
    country: 'US',
    industry: 'Semiconductors',
    eps: 2.10,
    currentPrice: 145.50,
    currency: '$',
    defaultTargetPe: 38,
    tradingViewSymbol: 'NASDAQ:AMD',
    naverTicker: 'AMD.O',
  },

  // ================= VIETNAM (VN) =================
  {
    id: 'VN_VNM',
    ticker: 'VNM',
    name: 'Vinamilk',
    koreanName: '비나밀크',
    country: 'VN',
    industry: 'Food Processing',
    eps: 4120,
    currentPrice: 68500,
    currency: '₫',
    defaultTargetPe: 15,
    tradingViewSymbol: 'HOSE:VNM',
    naverTicker: 'VNM.HM',
  },
  {
    id: 'VN_VCB',
    ticker: 'VCB',
    name: 'Vietcombank',
    koreanName: '비엣콤뱅크',
    country: 'VN',
    industry: 'Banking',
    eps: 5890,
    currentPrice: 89200,
    currency: '₫',
    defaultTargetPe: 12,
    tradingViewSymbol: 'HOSE:VCB',
    naverTicker: 'VCB.HM',
  },
  {
    id: 'VN_HPG',
    ticker: 'HPG',
    name: 'Hoa Phat Group',
    koreanName: '호아팟 그룹 (철강)',
    country: 'VN',
    industry: 'Steel & Materials',
    eps: 2150,
    currentPrice: 25400,
    currency: '₫',
    defaultTargetPe: 10,
    tradingViewSymbol: 'HOSE:HPG',
    naverTicker: 'HPG.HM',
  },
  {
    id: 'VN_FPT',
    ticker: 'FPT',
    name: 'FPT Corporation',
    koreanName: 'FPT 그룹 (IT/통신)',
    country: 'VN',
    industry: 'IT Services',
    eps: 7950,
    currentPrice: 132000,
    currency: '₫',
    defaultTargetPe: 18,
    tradingViewSymbol: 'HOSE:FPT',
    naverTicker: 'FPT.HM',
  },
  {
    id: 'VN_MWG',
    ticker: 'MWG',
    name: 'Mobile World Group',
    koreanName: '모바일월드 (유통)',
    country: 'VN',
    industry: 'Retail',
    eps: 3820,
    currentPrice: 64500,
    currency: '₫',
    defaultTargetPe: 14,
    tradingViewSymbol: 'HOSE:MWG',
    naverTicker: 'MWG.HM',
  },
  {
    id: 'VN_TCB',
    ticker: 'TCB',
    name: 'Techcombank',
    koreanName: '테크콤뱅크',
    country: 'VN',
    industry: 'Banking',
    eps: 4950,
    currentPrice: 22800,
    currency: '₫',
    defaultTargetPe: 8,
    tradingViewSymbol: 'HOSE:TCB',
    naverTicker: 'TCB.HM',
  },
  {
    id: 'VN_SSI',
    ticker: 'SSI',
    name: 'SSI Securities',
    koreanName: 'SSI 증권',
    country: 'VN',
    industry: 'Financial Services',
    eps: 1850,
    currentPrice: 32500,
    currency: '₫',
    defaultTargetPe: 14,
    tradingViewSymbol: 'HOSE:SSI',
    naverTicker: 'SSI.HM',
  }
];

async function importStocks() {
  console.log('Starting expanded stock import to Firestore...');
  const batch = db.batch();
  
  for (const stock of MOCK_STOCKS) {
    const docRef = db.collection('stocks').doc(stock.id);
    batch.set(docRef, {
      ...stock,
      lastUpdated: new Date().toISOString()
    });
    console.log(`Prepared import for: ${stock.name} (${stock.id})`);
  }
  
  await batch.commit();
  console.log('Successfully imported all expanded mock stocks to Firestore!');
}

importStocks().catch(console.error);
